### ISSUE TITLE
General Section Review Partners Page 1-6

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#1]
Explanation:

To carry out the general review of the pages in the `Partners` views, the following must be taken into account: a site was made based on an existing one, with the intention of migrating that WordPress site to React.js, you should consult with the [original site] (http://spgatsbystg.wpengine.com/), considering the list. For the review of these pages, the header and footer will not be taken into account, since these components are global and can be seen in all views.

URLof the page:
[WordPress Site](https://spgatsbystg.wpengine.com/)
[Site in ReactJs](https://wwwsimplepracticegatsbystaging.gatsbyjs.io/)

- [ ] Revision of color and typography of the Texts
- [ ] Review Shadows
- [ ] Review Forms
- [ ] Text sizes
- [ ] Image sizes
- [ ] Review of different screen sizes, Sizes: 320X538, 375X538, 425X538, 768X538, 1024X538, 1440X538.
- [ ] The page we are making must be as similar and visually consistent with the existing one.

### Pages to review:

React.js: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/
WordPress: http://spgatsbystg.wpengine.com/partners/

React.js: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/creative-therapy-umbrella/
WordPress: http://spgatsbystg.wpengine.com/partners/creative-therapy-umbrella/

React.js: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/speechiesideup/
WordPress: https://spgatsbystg.wpengine.com/partners/speechiesideup/

React.js: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/tnota/
WordPress: https://spgatsbystg.wpengine.com/partners/tnota/

React.js: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/digitalslp/
WordPress: https://spgatsbystg.wpengine.com/partners/partners/digitalslp/

React.js: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/mentally-fit/
WordPress: https://spgatsbystg.wpengine.com/partners/partners/mentally-fit/

**Comment by Katsu08** [comment]
Paragraph original:
![image](https://user-images.githubusercontent.com/66505715/160473816-a0baa196-ca72-47f1-a875-9f0d177c95ee.png)

Paragraph in Gatsby:
![image](https://user-images.githubusercontent.com/66505715/160473831-e4a788ff-c90e-4232-bf70-1bc86a997ae4.png)

I already have fixed this error
