### ISSUE TITLE
Link clip out of margin

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#100]
### Explanation
In the "Author" box the link clip to Israel Laguan is out of range, cut off for all resolutions.

**Actual result:**
In the "Author" box the link clip to Israel Laguan is cut off.

**Expected result:**
That in the "Author" box the link clip to Israel Laguan be seen in its entirety.

*Screen size:*
1024x633

### Screenshots

![image](https://user-images.githubusercontent.com/74306449/166847818-ca7b2572-196c-4ca1-91f7-950ceb54ab58.png)

### Check list
This issue can be closed when the following tasks are completed:
- Verify that the Israel Liguan link clip is viewed in full for all resolutions.

  ### References

https://github.com/Israel-Laguan/parrot-echo
the error is also repeated in:
https://github.com/Israel-Laguan/HTML-CSS-JS-Webpack-starter
https://github.com/Israel-Laguan/express-graphql-mongoose

**Comment by Israel-Laguan** [comment]
This one is a problem with Github, so it's impossible for us to change, so this issue is invalid
