### ISSUE TITLE
Margin error for resolution 320,375x633

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#101]
### Explanation
In the "Author" box margin error for resolution 375x633 and 320x633.

**Actual result:**
In the "Author" box for resolution 320 and 375 x633, the box on the right side is cut off.
**Expected result:**
That in the "Author" box for resolution 320 and 375 x633 the full screen is seen like the other resolutions.

*Screen size:*
320x633
375x633

### Screenshots
![image](https://user-images.githubusercontent.com/74306449/166853145-92539fea-fd44-46ef-b916-637bbb38c7cc.png)

![image](https://user-images.githubusercontent.com/74306449/166853174-417de2d7-d861-44c7-9161-e6bec02bbef4.png)

### Check list
This issue can be closed when the following tasks are completed:
- Verify that the screens are complete for the specified resolutions.

  ### References
https://github.com/Israel-Laguan/parrot-echo
the error is also repeated in:
https://github.com/Israel-Laguan/HTML-CSS-JS-Webpack-starter
https://github.com/Israel-Laguan/express-graphql-mongoose

**Comment by Israel-Laguan** [comment]
Sadly, this is an issue from Github, so we can not modify it
