### ISSUE TITLE
Different Reference Icons In "Show your support"  /  Diferentes Íconos De Referencia En "Muestra Tu Apoyo"

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#102]
### Explanation:

Different reference in "Show your support" to access icons8 between Laguan/parrot and Laguan/HTML.

**Current result:**
In "Show your support", the way to access icons8 is different between Laguan/parrot and Laguan/HTML.

**Expected result:**
That in "Show your support" the way to access icons8 is the same in Laguan/parrot and Laguan/HTML.

*Screen size:*
Full screen.

### Screenshots:
![image](https://user-images.githubusercontent.com/74306449/166854848-e96e8351-d299-4461-a80f-34ceaa5a1b94.png)

![image](https://user-images.githubusercontent.com/74306449/166854885-fd8cd5d4-03b9-4181-aa63-9dc303857187.png)

### Check list:
This issue can be closed when the following tasks are completed:
- Verify that the icon is the same for Laguan/parrot and Laguan/HTML.

  ### References:
https://github.com/Israel-Laguan/parrot-echo
https://github.com/Israel-Laguan/HTML-CSS-JS-Webpack-starter

Spanish Version:

### Explicación:

Existe una referencia distinta en "Muestra tu apoyo" para acceder a icons8, entre Laguan/parrot y Laguan/HTML.

**Resultado actual:**
En "Muestra tu apoyo" la forma de acceder a icons8 es diferente entre Laguan/parrot y Laguan/HTML.

**Resultado Esperado:**
Que en "Muestra tu apoyo" la forma de acceder a icons8 sea la misma en Laguan/parrot y Laguan/HTML.

*Tamaño de pantalla:*
Pantalla completa.

### Capturas de pantalla:
![imagen](https://user-images.githubusercontent.com/74306449/166854848-e96e8351-d299-4461-a80f-34ceaa5a1b94.png)

![imagen](https://user-images.githubusercontent.com/74306449/166854885-fd8cd5d4-03b9-4181-aa63-9dc303857187.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
- Verificar que el ícono sea el mismo para Laguan/parrot y Laguan/HTML.

  ### Referencias:
https://github.com/Israel-Laguan/parrot-echo
https://github.com/Israel-Laguan/HTML-CSS-JS-Webpack-starter

**Comment by Israel-Laguan** [comment]
Between them, what do you think is the best way, @angelik0828?

**Comment by angelik0828** [comment]
I think the link is better seen without the icon gives the patience to click on the most understan

**Comment by Israel-Laguan** [comment]
> I think the link is better seen without the icon gives the patience to click on the most understan

Please modify the description above with this in mind, thanks for feedback

**Comment by Dajava02** [comment]
I have created a solution for this issue, i changed the icon for a link https://github.com/Israel-Laguan/parrot-echo/pull/37
