### ISSUE TITLE
text thickness bug - fast-shopping-backend

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#104]
### Explanation
The text in the image does not have the same thickness, it is recommended that the thickness in the Code Style text be the same as the Standard text, since it would be better when viewing the image.

**Actual result:** the thickness in the Code Style text does not match the Standard text.

**Expected result:** the thickness of the Code Style text matches the Standard text.

*Screen size:* all screen

### Screenshots

Our: 
![image](https://user-images.githubusercontent.com/103531307/166855057-b2d4057f-d3d2-4e49-ba46-bf9b6ebfd537.png)

### Checklist
This issue can be closed when the following tasks are complete:
 
 - [ ] the thickness of the texts is the same.

 
### References

Our: https://github.com/Israel-Laguan/fast-shopping-backend

**Comment by Israel-Laguan** [comment]
That is an image, coming from external source, so it can not be modified
