### ISSUE TITLE
Error Between Logo And Text Spaces - Fast-Shopping-Backend  /  Error Entre El Logotipo Y Los Espacios De Texto - Fast-Shopping-Backend

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#105]
### Explanation:

It is recommended that between each logo and each text there is the same space.

**Current result:** 
Spaces between logo and text are not as expected.

**Expected result:**
 That between logo and text there is the same space.

*Screen size:*
 full screen.

### Screenshots:
Ours: 
![image](https://user-images.githubusercontent.com/103531307/166857829-b910e194-3f74-4e20-8734-afd3dd66736a.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] There is equal space between each logo and each text.

### References:
Ours: https://github.com/Israel-Laguan/fast-shopping-backend

Spanish Version:

### Explicación:

Se recomienda que entre cada logotipo y cada texto haya el mismo espacio.

**Resultado actual:** 
Los espacios entre el logotipo y el texto no son los esperados.

**Resultado esperado:**
 Que entre logo y texto hay el mismo espacio.

*Tamaño de la pantalla:*
 Pantalla completa.

### Capturas de pantalla:
Nuestra:: 
! [imagen] (https://user-images.githubusercontent.com/103531307/166857829-b910e194-3f74-4e20-8734-afd3dd66736a.png)

### Lista de verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
 
- [ ] Que haya un espacio igual entre cada logotipo y cada texto.

### Referencias:
La nuestra: https://github.com/Israel-Laguan/fast-shopping-backend

**Comment by Dajava02** [comment]
Can someone assign me this Issue?

**Comment by Dajava02** [comment]
I made a solution for this issue, I fixed the space between the texts and logos and activated the link to linkedin https://github.com/Israel-Laguan/fast-shopping-backend/pull/20
