### ISSUE TITLE
Font bug - shopeasy-ruby-backend

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#106]
### Explanation
On the right side of each box, the font does not coincide with the left side.

**Actual result:** Different font.

**Expected result:** Match the same font.

*Screen size:* all screen 

### Screenshots

Our: 
![image](https://user-images.githubusercontent.com/103531307/166959811-5f430f8c-1a13-4ade-bdd1-209b0b1d9729.png)

![image](https://user-images.githubusercontent.com/103531307/166960511-f3efc655-e623-4d7e-9dfc-5c97a3f92cc0.png)

![image](https://user-images.githubusercontent.com/103531307/166962327-c99e8d6c-9bef-470b-aa99-643053999bec.png)

### Checklist
This issue can be closed when the following tasks are complete:
 
 - [ ] the font is the same.

 
### References

Our: https://github.com/Israel-Laguan/shopeasy-ruby-backend

**Comment by Israel-Laguan** [comment]
That also is external/non-fixable issue, please note is an image coming form other place
