### ISSUE TITLE
Unexpected colour - arduino-relay-app

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#108]
### Explanation
It is recommended that the fill of the text 0 CLOSED be yellow, matching the color with that of the left side 1 OPEN.

**Actual result:** The fill of the 0 CLOSED text is green.

**Expected result:** That the padding 0 CLOSED be yellow.

*Screen size:* all screen 

### Screenshots
Our: 
![image](https://user-images.githubusercontent.com/103531307/166982618-c0dfe2f5-c29e-4653-8334-fae98ecda8cd.png)

### Checklist
This issue can be closed when the following tasks are complete:
 
 - [ ] The fill of the 0 CLOSED text is yellow.
 
### References

Our: https://github.com/Israel-Laguan/arduino-relay-app

**Comment by Israel-Laguan** [comment]
Hmm colors are not dependent on the value, and that is not defined on our side
