### ISSUE TITLE
Size Is Not As Expected -  TicTacToe-JS  /  El Tamaño No Es El Esperado - TicTacToe-JS

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#109]
### Explanation:

The size of the buttons is very small, it is recommended to increase the size of the buttons and reduce the size of the logo in half.

**Current result:**  
The size of the buttons is very small and the size of the logo in the middle is very large.

**Expected result:**
 That the size of the buttons is bigger and the half logo is smaller.

*Screen size:*
 Full screen. 

### Screenshots:
Ours: 
![image](https://user-images.githubusercontent.com/103531307/167005456-404bed50-799c-4e86-8de1-ce7a00ded95d.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] Sizes are as expected.
 
### References:
Our: https://github.com/Israel-Laguan/TicTacToe-JS

Spanish Version:

### Explicación:

El tamaño de los botones es muy pequeño, se recomienda aumentar el tamaño de los botones y reducir el tamaño del logotipo a la mitad.

**Resultado actual:**  
El tamaño de los botones es muy pequeño y el tamaño del logotipo en el medio es muy grande.

**Resultado esperado:**
 Que el tamaño de los botones es más grande y la mitad del logotipo es más pequeño.

*Tamaño de la pantalla:*
 Pantalla completa. 

### Capturas de pantalla:
La nuestra: 
! [imagen] (https://user-images.githubusercontent.com/103531307/167005456-404bed50-799c-4e86-8de1-ce7a00ded95d.png)

### Lista de verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
 
- [ ] Los tamaños son los esperados.
 
### Referencias:
La nuestra: https://github.com/Israel-Laguan/TicTacToe-JS

**Comment by Israel-Laguan** [comment]
It can be changed applying styles from here

https://shields.io/

TL:DR

Change `?style=plastic` in the label URL to `?style=for-the-badge`

**Comment by Dajava02** [comment]
Can I be assigned to this issue?

**Comment by Dajava02** [comment]
I created a solution for this issue, I increased the size of the buttons https://github.com/Israel-Laguan/TicTacToe-JS/pull/28
