### ISSUE TITLE
  Link Error - Report  /  Error De Enlace - Reportar

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#111]
### Explanation:

The http://localhost:3000 appears in the text but clicking on it does not open the link.

**Current result:**
It does not open the link.

**Expected result:** 
 The link opens me to the next page.

*Screen size:*
 Full  screen.

### Screenshots:
Ours: 
![image](https://user-images.githubusercontent.com/103531307/167033500-7438665c-81fd-4273-9958-1981286f035f.png)

![image](https://user-images.githubusercontent.com/103531307/167033586-b4005381-7547-4c21-ac5b-a6207d54a7fb.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] Clicking the link takes me to the next page.

### References:
Our: https://github.com/Israel-Laguan/reporting

-----------------------------------------------------------------

Spanish Version:

### Explicación:

El http://localhost:3000 aparece en el texto pero al hacer clic en él no se abre el enlace.

**Resultado actual:**
No abre el enlace.

**Resultado Esperado:**
 Que el enlace me abra la página siguiente.

*Tamaño de pantalla:*
 Pantalla completa.

### Capturas de pantalla:

Nuestra:
![imagen](https://user-images.githubusercontent.com/103531307/167033500-7438665c-81fd-4273-9958-1981286f035f.png)

![imagen](https://user-images.githubusercontent.com/103531307/167033586-b4005381-7547-4c21-ac5b-a6207d54a7fb.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completan las siguientes tareas:
 
 - [ ] Hacer clic en el enlace me lleva a la página siguiente.

### Referencias:

Nuestro: https://github.com/Israel-Laguan/reporting

**Comment by arodriguezl9302** [comment]
I would like to be assigned to this task  @Israel-Laguan @Katsu08 @e-azocar

**Comment by e-azocar** [comment]
That link needs the app running, so, I think we should leave it like this

**Comment by Israel-Laguan** [comment]
Oh, the solution is to convert to a normal string, so instead of [http://localhost:3000]() (<-- note is blue) just has to be converted to `http://localhost:3000`

**Comment by angelik0828** [comment]
@arodriguezl9302 this can be verified

**Comment by Coolhatena** [comment]
The link `http://localhost:3000` is not in the readme document of the repo, has this issue already been solved?

**Comment by Israel-Laguan** [comment]
> The link `http://localhost:3000` is not in the readme document of the repo, has this issue already been solved?

Seems like in this case it should be ADDED hehe You can copy the instructions to run in dev environment here from other repo

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/173864679-a349c19d-242f-4114-b864-34b1d8c0128b.png)

**Comment by e-azocar** [comment]
@hector-trompis issue fixed
