### ISSUE TITLE
Add More Information To The README - Report  /  Agregar Más Información Al Archivo README - Reportar

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#112]
[### Explanation:

It is recommended to add more information to the README, either in text or an image, so that the user can understand the content.

**Current result:** 
The README lacks clear information to be understood by the user.

**Expected result:**
 In the README there is clear information to be understood by the user.

*Screen size:* 
Full screen. 

### Screenshots:
Ours: 
![image](https://user-images.githubusercontent.com/103531307/167035365-bb874145-9e1e-4465-bee8-d34acf8673ac.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] The content of the README contains information in which the user understands the content.
 contains information in which the user understands the content.
 contains information in which the user understands the content.

### References:
Ours: https://github.com/Israel-Laguan/reporting

Spanish Version:

[### Explicación:

Se recomienda agregar más información al LÉAME, ya sea en texto o en una imagen, para que el usuario pueda entender el contenido.

**Resultado actual:**
El README carece de información clara para ser entendido por el usuario.

**Resultado Esperado:**
  En el README hay información clara para ser entendida por el usuario.

*Tamaño de pantalla:*
Pantalla completa.

### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167035365-bb874145-9e1e-4465-bee8-d34acf8673ac.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completan las siguientes tareas:
 
  - [ ] El contenido del README contiene información en la que el usuario entiende el contenido.
  contiene información en la que el usuario entiende el contenido.
  contiene información en la que el usuario entiende el contenido.

### Referencias:
Nuestro: https://github.com/Israel-Laguan/reporting

**Comment by mdrianislam0or1** [comment]
Edit Readme file.

![reporting](https://user-images.githubusercontent.com/67714964/168608836-7a6073b2-d564-4018-bdeb-5ae0f9ae1e66.jpg)

**Comment by heliomar-pena** [comment]
@mdrianislam0or1 can you please add a link to test your solution?

**Comment by mdrianislam0or1** [comment]
@Katsu08 What do you want? I added a Pull request to that repo.

**Comment by heliomar-pena** [comment]
Please share here the pull request URL to easy access

**Comment by mdrianislam0or1** [comment]
https://github.com/Israel-Laguan/reporting/pull/40

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171285969-b6fcffbf-d36d-42bb-ab22-c2f45bd5e5bc.png)
