### ISSUE TITLE
Missing Content - Reporting  /  Contenido Faltante - Informes

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#113]
### Explanation:

It is recommended below the author information to add information Contributing, Show your support and License.

**Current result:**
 Contributing, Show your support and License content is missing.

**Expected result:**
 There is information about the content Contributing, Show your support and License.

*Screen size:*
Full screen.

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167037165-4692b462-d157-4efa-8fdc-68d78a56328d.png)

### Checklist:

This issue can be closed when the following tasks are completed:
 
 - [ ] Information and content are complete.
 
### References:
Our: https://github.com/Israel-Laguan/reporting

Spanish Version:

### Explicación:

Se recomienda debajo de la información del autor agregar información Contribuyendo, Mostrar su apoyo y Licencia.

**Resultado actual:**
  Falta contenido de Contributing, Show your support y License.

**Resultado Esperado:**
  Hay información sobre el contenido Contribuyendo, Muestra tu apoyo y Licencia.

*Tamaño de pantalla:*
Toda la pantalla.

### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167037165-4692b462-d157-4efa-8fdc-68d78a56328d.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
 
  - [ ] La información y el contenido están completos.
 
### Referencias:
Nuestra: https://github.com/Israel-Laguan/reporting

**Comment by mdrianislam0or1** [comment]
Added Missing Contents


![1](https://user-images.githubusercontent.com/67714964/168355621-4ac42781-0ba7-45f0-90d2-a47e6578d18c.jpg)

**Comment by heliomar-pena** [comment]
> Added Missing Contents
> 
> ![1](https://user-images.githubusercontent.com/67714964/168355621-4ac42781-0ba7-45f0-90d2-a47e6578d18c.jpg)

Can you add a link to test your solution?

**Comment by mdrianislam0or1** [comment]
@Katsu08 What do you want? I added a Pull request to that repo.

**Comment by heliomar-pena** [comment]
> @Katsu08 What do you want? I added a Pull request to that repo.

Please share the pull request link here to easy access

**Comment by mdrianislam0or1** [comment]
https://github.com/Israel-Laguan/reporting/pull/39

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171284298-25e80745-a7e1-49c1-b5c9-9c199106e1e6.png)
