### ISSUE TITLE
It Is Not Understood What "Icon From" Refers To  /  No Se Entiende A Qué Se Refiere "Icon From"

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#115]
### Explanation:

It is not clear what IT means, because IT says:
(icon from:) and below (icon by icons8).

**Current result:**
In "Show your support" it is not understood what "icon from:" and "icon by icons8" refer to.

**Expected result:**
That in "Show your support" it is understood that "icon from:" and "icon by icons8" refer.

*Screen size:*
1024x633

### Screenshots:
![image](https://user-images.githubusercontent.com/74306449/167052619-86cd40bc-dbb9-4b51-a9c2-79ed6128cbe0.png)

### Check list:
This issue can be closed when the following tasks are completed:
-That the explained details be modified.

### References:
https://github.com/Israel-Laguan/credit-card-component

Spanish Version:

### Explicación:

No está claro qué significa TI, porque dice:
(ícono de:) y debajo (ícono de icons8)

**Resultado actual:**
En "Muestra tu apoyo" no se entiende a qué se refieren "icon from:" e "icon by icons8".

**Resultado Esperado:**
Que en "Muestra tu apoyo" se entienda que se refieren a "icon from:" e "icon by icons8".

*Tamaño de pantalla:*
1024x633

### Capturas de pantalla:
![imagen](https://user-images.githubusercontent.com/74306449/167052619-86cd40bc-dbb9-4b51-a9c2-79ed6128cbe0.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
-Que se modifiquen los detalles explicados.

### Referencias:
https://github.com/Israel-Laguan/credit-card-component

**Comment by Dajava02** [comment]
I made a solution for this issue, I removed "icon by" https://github.com/Israel-Laguan/credit-card-component/pull/17
