### ISSUE TITLE
 Remove Shopeasy-Ruby -Backend Content  /  Eliminar El Contenido De Shopeasy-Ruby-Backend

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#116]
### Explanation:

It is recommended to remove Versions and Packages as they have no published content.

**Current result:** 
Versions and Packages are in the content.

**Expected result:** 
That Versions and Packages are not in the content.

*Screen size:* 
 Full screen. 

### Screenshots:
Ours: 
![image](https://user-images.githubusercontent.com/103531307/167054310-8b5a9d2b-30ec-4001-9b5d-2f6f6b94e56a.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] They are not in the Versions and Packages content since they do not have anything published.

### References:
Our: https://github.com/Israel-Laguan/shopeasy-ruby-backend

Spanish Version:

### Explicación:

Se recomienda eliminar Versiones y Paquetes ya que no tienen contenido publicado.

**Resultado actual:**
Las versiones y los paquetes están en el contenido.

**Resultado Esperado:**
Qué versiones y paquetes no están en el contenido.

*Tamaño de pantalla:*
    Pantalla completa.

### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167054310-8b5a9d2b-30ec-4001-9b5d-2f6f6b94e56a.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
 
    - [ ] No están en el contenido de Versiones y Paquetes ya que no tienen nada publicado.

### Referencias:
Nuestra: https://github.com/Israel-Laguan/shopeasy-ruby-backend

**Comment by hector-trompis** [comment]
passed to administration
