### ISSUE TITLE
Improve The Authors Section Style  /  Mejorar El Estilo De La Sección De Autores 

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#117]
### Explanation:

The goal is to improve the style in the "Authors" section, the box looks noticeably smaller than the line above, which makes it look off center, plus it's cropped for this and all other resolutions.

**Current result:**
In the "Authors" session, the box looks smaller than the line above and shows it cut off.

**Expected result:**
In the "Authors" session, the box should be seen parallel to the line and show all the complete information.

*Screen size:*
1-1024x633
2-768x633
3-425x633
4-375x633
### Screenshots:
1-
![image](https://user-images.githubusercontent.com/74306449/167055561-42cf5ac4-2415-42a6-a1eb-eeab766f79c0.png)
2-
![image](https://user-images.githubusercontent.com/74306449/167055629-1832888b-ca57-4854-8dd1-16f77285df2c.png)
3-
![image](https://user-images.githubusercontent.com/74306449/167055690-1ee345ae-168a-4e28-821a-8ea3bfbcc17f.png)
4-
![image](https://user-images.githubusercontent.com/74306449/167055770-3799b7c2-d2ba-4a7d-b7fc-56ad1fd2637d.png)

### Check list:

This issue can be closed when the following tasks are completed:
-That the views on the different screens are modified.

### References:
https://github.com/Israel-Laguan/Shopeasy

Spanish Version:

### Explicación:
El objetivo es mejorar el estilo en la sección "Autores", el cuadro se ve ciertamente más pequeño que la línea de arriba, lo que hace que se vea descentrado, además está recortado para esto y todas las demás resoluciones.

**Resultado real:**
En la sesión "Autores", el cuadro parece más pequeño que la línea anterior y se muestra recortado.

**Resultado esperado:**
En la sesión de "Autores", el recuadro debe verse en paralelo a la línea y mostrar toda la información completa.

*Tamaño de pantalla:*
1-1024x633
2-768x633
3-425x633
4-375x633
### Capturas de pantalla:
1-
![imagen](https://user-images.githubusercontent.com/74306449/167055561-42cf5ac4-2415-42a6-a1eb-eeab766f79c0.png)
2-
![imagen](https://user-images.githubusercontent.com/74306449/167055629-1832888b-ca57-4854-8dd1-16f77285df2c.png)
3-
![imagen](https://user-images.githubusercontent.com/74306449/167055690-1ee345ae-168a-4e28-821a-8ea3bfbcc17f.png)
4-
![imagen](https://user-images.githubusercontent.com/74306449/167055770-3799b7c2-d2ba-4a7d-b7fc-56ad1fd2637d.png)

### Lista de verificación:

Este problema se puede cerrar cuando se completen las siguientes tareas:
-Que se modifiquen las vistas en las diferentes pantallas.

### Referencias:
https://github.com/Israel-Laguan/Shopeasy

**Comment by Israel-Laguan** [comment]
I would say "Lets improve the authors section style"

**Comment by e-azocar** [comment]
@Israel-Laguan can we change those styles with Markdown?

**Comment by Israel-Laguan** [comment]
Hmm maybe we would need to check first what is possible, then propose a valid way to improve

**Comment by Coolhatena** [comment]
I redid the table using Markdown and now a lot more content is visible in the smaller resolutions, however as github doesn't allow css in Markdown I find kinda epic to display the full content in the 375x633 resolution 

Pull request: https://github.com/Israel-Laguan/Shopeasy/pull/15

**Comment by Israel-Laguan** [comment]
@angelik0828 what do you think would be a good proposal here, visually?

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171156793-d88e7083-f005-439f-a929-fc160b639594.png)
