### ISSUE TITLE
To Get Better Image - HTML-LESS-JS-No-Webpack-Starter  /  Para Obtener Una Mejor Imagen: HTML-LESS-JS-No-Webpack-Starter

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#118]
### Explanation:

It is recommended to put another image which specifies the user about the content of the page.

**Current result:** Image is not clear on the content of the page.

**Expected result:** That there is a clear image that allows the user to understand the content of the page.

*Screen size:* The whole screen 

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167056910-b599e531-079b-4aff-8426-7b4a591cab5c.png)

### Checklist:

This issue can be closed when the following tasks are completed:
 
 - [ ] The image allows the user to understand the content of the page.
 
### References:

Our: https://github.com/Israel-Laguan/HTML-LESS-JS-no-webpack-starter

Spanish Version:

### Explicación:

Se recomienda poner otra imagen que especifique al usuario sobre el contenido de la página.

**Resultado actual:** La imagen no está clara en el contenido de la página.

**Resultado esperado:** Que exista una imagen clara que permita al usuario entender el contenido de la página.

*Tamaño de pantalla:* Toda la pantalla

### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167056910-b599e531-079b-4aff-8426-7b4a591cab5c.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
 
  - [ ] La imagen permite al usuario comprender el contenido de la página.
 
### Referencias:
Nuestro: https://github.com/Israel-Laguan/HTML-LESS-JS-no-webpack-starter

**Comment by mdrianislam0or1** [comment]
Implement Better Image.

![fix1](https://user-images.githubusercontent.com/67714964/168345159-4fadde1d-bc8b-4741-a8f6-60cace6dc789.jpg)

**Comment by mdrianislam0or1** [comment]
https://github.com/Israel-Laguan/HTML-LESS-JS-no-webpack-starter/pull/10

**Comment by roberto-97c** [comment]
![image](https://user-images.githubusercontent.com/103531307/171282469-7990d372-0c95-4f0c-a77e-9a8abb75d89b.png)
