### ISSUE TITLE
Error in "About" missing link

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#120]
### Explanation
In "About" you do not have the link that explains the content of the page.

**Current result:**
When entering the Proximity Post-it page, in "About" you do not have the link that explains the content of the page.

**Expected result:**
That when entering the Proximity Post-it page, in "About" it shows the link that explains the content of the page.

*Screen size:*

the whole screen

### Screenshots

![image](https://user-images.githubusercontent.com/74306449/167058274-d511277e-96c6-4d22-a8f8-4549597f4dc9.png)

### Check list
This issue can be closed when the following tasks are completed:
-That the indicated error be modified.

 ### References

https://github.com/Israel-Laguan/proximity-post-it

**Comment by arodriguezl9302** [comment]
I would like to be assigned to this task  @Israel-Laguan @Katsu08 @e-azocar

**Comment by Israel-Laguan** [comment]
Just to be clear, this "LINK" involves deploy the repo code into something like netlify or similar
