### ISSUE TITLE
   Link Error- React-Cra-Ts-Testing-Practice  /  Error De Enlace - React-Cra-Ts-Testing-Practice #125

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#125]
### Explanation:

It is recommended to fix the links error as it does not open to the next page.

**Current result:** The link does not work.

**Expected result:** That when clicking on the link opens it.

*Screen size:*  Full screen.

### Screenshots.
Our:
![image](https://user-images.githubusercontent.com/103531307/167206081-4bea93d8-6eae-403a-805b-3424ae68cf20.png)

![image](https://user-images.githubusercontent.com/103531307/167206104-de5376f4-f56b-4b72-8baa-6d395a612e89.png)

### Checklist:
 
This issue can be closed when the following tasks are completed:
 
 - [ ] When the link http://localhost:3000/ opens when clicked.

### References:
Our: https://github.com/Israel-Laguan/react-cra-ts-testing-practice

**Spanish Version**

### Explicación:
Se recomienda corregir el error de enlaces ya que no abre a la página siguiente.

**Resultado actual:** El enlace no funciona.

**Resultado esperado:** Que al hacer clic en el enlace se abra.

*Tamaño de pantalla:* Pantalla completa.

### Capturas de pantalla.
Nuestra:
![imagen](https://user-images.githubusercontent.com/103531307/167206081-4bea93d8-6eae-403a-805b-3424ae68cf20.png)

![imagen](https://user-images.githubusercontent.com/103531307/167206104-de5376f4-f56b-4b72-8baa-6d395a612e89.png)

### Lista de Verificación:
 
Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Que abra el enlace http://localhost:3000/ al hacer clic.

### Referencias:
Nuestro: https://github.com/Israel-Laguan/react-cra-ts-testing-practice

**Comment by Coolhatena** [comment]
Done! The link cannot be opened from README.md because its only available locally during development, but i changed the style of the link to something more sober to avoid confusion.

I already sent the pull request with the solution: https://github.com/TheRandomCrew/react-cra-ts-testing-practice/pull/6

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/173065374-28fe450c-9b41-4965-9134-895612e03fc9.png)
fixed!!

**Comment by Coolhatena** [comment]
Could someone please change this issue to EE-3 as we agreed?
