### ISSUE TITLE
Improve Presentation -  Github-Issue-Templates  /  Mejorar La Presentación - Github-Issue-Templates

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#127]
### Explanation:
It is recommended to briefly explain why the texts are underlined, so that the user can understand it.

**Current result:** Texts underlined with a line.

**Expected result:** Improve the presentation of these.

*Screen size:* Full screen.
### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167218203-5f303256-728f-4877-b3ce-4836c8411711.png)

![image](https://user-images.githubusercontent.com/103531307/167218232-7e72189e-1a23-4f49-acca-eed66010ce99.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] When the presentation has been improved.
 
### References:
Our: https://github.com/Israel-Laguan/github-issue-templates

Spanish Version:

### Explicación:
Se recomienda explicar brevemente por qué los textos están subrayados, para que el usuario pueda entenderlo.

**Resultado actual:** Textos subrayados con una línea.

**Resultado esperado:** Mejorar la presentación de estos.

*Tamaño de pantalla:* Pantalla completa.
### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167218203-5f303256-728f-4877-b3ce-4836c8411711.png)

![imagen](https://user-images.githubusercontent.com/103531307/167218232-7e72189e-1a23-4f49-acca-eed66010ce99.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Cuando se haya mejorado la presentación.
 
### Referencias:
Nuestra: https://github.com/Israel-Laguan/github-issue-templates

**Comment by Israel-Laguan** [comment]
This was not code from me, it is a fork, so changing it is no priority at all.

Will close this issue

CC: @hector-trompis
