### ISSUE TITLE
 Misaligned Text - Home

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#13]
### Explanation:
On the main page, the text in the blue section is misaligned at this resolution.

*Screen size:* (768X532 )

### Screenshots:

Original: (![image](https://user-images.githubusercontent.com/4030477/160648161-65525204-a800-45d6-a5a8-24fe6bc263a6.png))
Our: (![image](https://user-images.githubusercontent.com/4030477/160647864-1c9b88f6-7edf-451e-b71d-1f891727514d.png))

### Checklist
 
 - [ ] Arrange text in resolution.
 - [ ] Check texts in a smaller resolution.
 
### References:
 
Original: https://spgatsbystg.wpengine.com/
Our: (https://wwwsimplepracticegatsbystaging.gtsb.io/)

**Comment by denisosuna** [comment]
fixed in https://github.com/simplepractice/www-simplepractice-gatsby/pull/new/fix/capterra-banner--text-in-responsive

**Comment by heliomar-pena** [comment]
@denisosuna Good work!
