### ISSUE TITLE
 Add More Content - Github-Issue-Templates  /  Agregar Más Contenido - Github-Issue-Templates

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#130]
### Explanation:
It is recommended to add images and content to the page.

**Actual result:** Missing content and images on the page.

**Expected result:** Let there be more content and images on the page.

*Screen size:*  Full screen. 

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167219540-1aa7cf14-a755-44a3-b4f2-565964243127.png)

![image](https://user-images.githubusercontent.com/103531307/167219572-08cfed1e-6563-44a5-88fc-4c3062a0b190.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] When there is more content and images.

### References:
Our: https://github.com/Israel-Laguan/github-issue-templates

Spanish Version:

**Explicación:**

Se recomienda agregar imágenes y contenido a la página.

**Resultado real:** Falta contenido e imágenes en la página.

**Resultado esperado:** Que haya más contenido e imágenes en la página.

*Tamaño de pantalla:* Pantalla completa.

### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167219540-1aa7cf14-a755-44a3-b4f2-565964243127.png)

![imagen](https://user-images.githubusercontent.com/103531307/167219572-08cfed1e-6563-44a5-88fc-4c3062a0b190.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Cuando haya más contenido e imágenes.

### Referencias:
Nuestra: https://github.com/Israel-Laguan/github-issue-template

**Comment by mdrianislam0or1** [comment]
Is there anyone who already working on that issue?

**Comment by mdrianislam0or1** [comment]
Added related link and content.

![fix](https://user-images.githubusercontent.com/67714964/169253315-54fa337f-c618-4b12-8c20-232094eab990.jpg)

**Comment by mdrianislam0or1** [comment]
https://github.com/root-code-software/github-issue-templates/pull/1

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171283951-3d9ddc2d-8bf8-496e-a2c9-a325c07cb560.png)
