### ISSUE TITLE
add link - github-issue-templates

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#131]
### Explanation
It is recommended to add a link on the content of the page.

**Actual result:** There is no link to the content of the page, the Releases and Packages have no content.

**Expected result:** That there is a link to the content of the page and there are no Releases and Packages since they have nothing published.

*Screen size:* all screen 

### Screenshots

Our: 
![image](https://user-images.githubusercontent.com/103531307/167220551-c89c1fec-242f-4ffc-87e8-ac53fd1b3cc3.png)

### Checklist
This issue can be closed when the following tasks are complete:
 
 - [ ] When there is a link to the content of the page and there are no Releases and Packages.

### References

Our: https://github.com/Israel-Laguan/github-issue-templates

**Comment by arodriguezl9302** [comment]
I would like to be assigned to this task  @Israel-Laguan @Katsu08 @e-azocar

**Comment by angelik0828** [comment]
when this task is reviewed and ready we will notify you, thank you for your interest

**Comment by heliomar-pena** [comment]
@Israel-Laguan this repo doesn't have page / package, it's simply documentation. @Israel-Laguan can you confirm please if this is a valid issue?

**Comment by Israel-Laguan** [comment]
Yeah, I think it's not valid 

please see if something in the original repo can be useful

https://github.com/stevemao/github-issue-templates
