### ISSUE TITLE
 Delete The Link That Says "Read The Article"  /  Borrar El Enlace Que Dice "Leer El Artículo"

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#132]
**Explanation:**
The icon does not correspond to the page and generates a link with an error.

**Current result:
When clicking on the "🖊️ Read the article" icon, it shows a blank screen that indicates the page is locked.

**Expected result:
Do not open the link so that it does not generate results.

**Screen size:
screenshots:
![image](https://user-images.githubusercontent.com/74306449/167224915-0ebfa2e8-9b02-4281-b99a-d9e1b910704c.png)

**Check list:
This issue can be closed when the following tasks are completed:
-That the indicated error be modified.

**References:
https://github.com/Israel-Laguan/Advanced-Building-Blocks---Bubble-Sort
https://github.com/Israel-Laguan/HTML-CSS-JS-Webpack-starter
https://github.com/Israel-Laguan/React-SaaS-E-Commerce-Starter
https://github.com/Israel-Laguan/Tic-Tac-Toe
https://github.com/Israel-Laguan/express-server-jwt
https://github.com/Israel-Laguan/FaircoinRPS
https://github.com/Israel-Laguan/textedit-app
https://github.com/Israel-Laguan/yjs-react-example
https://github.com/Israel-Laguan/microverse-trial-4
https://github.com/Israel-Laguan/microverse-trial-3.

-----------------------------------------------------------------

**Spanish Version**

**Explicación:**
El ícono no corresponde a la página y genera un enlace con error.

**Resultado actual:
Al hacer clic en el ícono "🖊️ Leer el artículo", muestra una pantalla en blanco que indica que la página está bloqueada.

**Resultado Esperado:
No abrir el enlace para que no genere resultados.

**Tamaño de pantalla:
**Capturas de pantalla:
![imagen](https://user-images.githubusercontent.com/74306449/167224915-0ebfa2e8-9b02-4281-b99a-d9e1b910704c.png)

**Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
-Que se modifique el error indicado.

**Referencias:
https://github.com/Israel-Laguan/Advanced-Building-Blocks---Bubble-Sort
https://github.com/Israel-Laguan/HTML-CSS-JS-Webpack-starter
https://github.com/Israel-Laguan/React-SaaS-E-Commerce-Starter
https://github.com/Israel-Laguan/Tic-Tac-Toe
https://github.com/Israel-Laguan/express-server-jwt
https://github.com/Israel-Laguan/FaircoinRPS
https://github.com/Israel-Laguan/textedit-app
https://github.com/Israel-Laguan/yjs-react-example
https://github.com/Israel-Laguan/microverse-trial-4
https://github.com/Israel-Laguan/microverse-trial-3

**Comment by e-azocar** [comment]
@Israel-Laguan what do you think can be the link in "Read the Article"?

**Comment by Israel-Laguan** [comment]
In the original README there was an article that referenced the repo, but in most of the others repos there is no article to reference. 

I think the task should be "Erase the link that says Read the Article"

**Comment by e-azocar** [comment]
@anaPiris please change the issue to "Erase the link that says Read the Article"

**Comment by anaceciliamolinares** [comment]
I cannot see the screen size. Please fix it.

**Comment by anaceciliamolinares** [comment]
There are other synonyms for erase, such as: "delete, remove, write off, cancel, undo", which are transparent and not as common, but which enrich our vocabulary.

**Comment by angelik0828** [comment]
@arodriguezl9302 Can this be checked now?

**Comment by e-azocar** [comment]
> @arodriguezl9302 Can this be checked now?

I think he didn't fix it

**Comment by angelik0828** [comment]
I'm pending

**Comment by Israel-Laguan** [comment]
If one dev will fix all the repos, I would consider increasing estimation point to EE-3 

@hector-trompis please coordinate on this

**Comment by Coolhatena** [comment]
@Israel-Laguan I'm going to take this issue, so, if i solve the problem in all the listed repos the estimation will increase to EE-3?

**Comment by hector-trompis** [comment]
Yes sir. So the stress estimate is 3.

**Comment by Coolhatena** [comment]
Done! ive sent the pull request to all the listed repos, im waiting for the approval

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/173059662-38612e3f-60b4-4c5a-96e9-9a538da85cbe.png)
I already checked all the repositories,  Fixed!!!

**Comment by Coolhatena** [comment]
Could someone please change this issue to EE-3 as we agreed?

**Comment by angelik0828** [comment]
yes @hector-trompis  did I mention that yes don't worry
