### ISSUE TITLE
In "Authors" As Shown Link  /  En "Autores" Como Se Muestra En El Enlace

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#133]
**Explanation:**
In "Authors", identify "Connect to my Linkedin" and "Verify my GitHub profile" in the same way as the mail, as a quick view there is a direct access and more visible.

Current result:
When entering the page and going to Authors, both for "Connect to my Linkedin" and for "Check my GitHub Profile" it is not marked in blue like the email.

Expected result:
That when entering the page and going to Authors, both to "Connect to my Linkedin" and to "Check my GitHub Profile" it is marked in blue just like the Email.

Screen size:
All screens

Screenshots:
![image](https://user-images.githubusercontent.com/74306449/167226983-057d678b-41b6-4f35-90f6-d8cac1f5d3aa.png)

Check list:
This issue can be closed when the following tasks are completed:
-If the modifications are approved, verify that they are carried out.

References:
https://github.com/Israel-Laguan/Advanced-Building-Blocks
https://github.com/Israel-Laguan/parrot-echo
https://github.com/Israel-Laguan/HTML-CSS-JS-Webpack-starter
https://github.com/Israel-Laguan/express-graphql-mongoose
https://github.com/Israel-Laguan/credit-card-component
https://github.com/Israel-Laguan/Shopeasy
https://github.com/Israel-Laguan/arduino-relay-app
https://github.com/Israel-Laguan/israel-laguan.github.io

Spanish Version:

**Explicación:**
En "Autores", identifica "Conectar a mi Linkedin" y "Verificar mi perfil de GitHub" de la misma manera que el correo, así como vista rápida. También tiene un acceso directo y más visible.

Resultado actual:
Al entrar a la página e ir a "Autores", tanto para "Conectar a mi Linkedin" como para "Consultar mi Perfil de GitHub", no está marcado en azul como el correo electrónico.

Resultado Esperado:
Que al entrar a la página e ir a "Autores", tanto a "Conectar a mi Linkedin" como a "Consultar mi Perfil de GitHub" se marque en azul, al igual que el Email.

Tamaño de pantalla:
Pantalla completa.

Capturas de pantalla:
![imagen](https://user-images.githubusercontent.com/74306449/167226983-057d678b-41b6-4f35-90f6-d8cac1f5d3aa.png)

Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
-Si se aprueban las modificaciones, verificar que se lleven a cabo.

Referencias:
https://github.com/Israel-Laguan/Advanced-Building-Blocks
https://github.com/Israel-Laguan/parrot-echo
https://github.com/Israel-Laguan/HTML-CSS-JS-Webpack-starter
https://github.com/Israel-Laguan/express-graphql-mongoose
https://github.com/Israel-Laguan/credit-card-component
https://github.com/Israel-Laguan/Shopeasy
https://github.com/Israel-Laguan/arduino-relay-app
https://github.com/Israel-Laguan/israel-laguan.github.io

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171166151-b5dd5faf-72e3-4145-80ce-def1e50cd505.png)
