### ISSUE TITLE
Page does not correspond to the link in: "Authors"

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#134]
Explanation
In "Authors", in Izaias Neto when clicking on the name redirects to a GitHub repository when it should show personal information to whom the name refers.

current result:
When entering the page and going to Authors and clicking on the name of Izaias Neto, it shows the GitHub repository of the same.

Expected result:
That when entering the page and going to Authors and clicking on the name of Izaias Neto, it shows personal information that refers to the name.

Screen size:
all screens

screenshots
![image](https://user-images.githubusercontent.com/74306449/167227661-e4383d51-c1d8-40bf-aee4-90c9c84dc423.png)

Check list
This issue can be closed when the following tasks are completed:
-That the indicated error be modified.

References
https://github.com/Israel-Laguan/Advanced-Building-Blocks---Bubble-Sort#show-your-support

**Comment by arodriguezl9302** [comment]
I would like to be assigned to this task  @Israel-Laguan @Katsu08 @e-azocar

**Comment by Israel-Laguan** [comment]
I think current behavior when clicking the image or name is expected

Maybe would be good to talk how we would like these things to work
