### ISSUE TITLE
Table Of Contents (Location) in Credit Card Component  /  Tabla De Contenido (Ubicación) En El Componente De Tarjeta De Crédito

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#136]
**Explanation:**

The table of contents should be at the very beginning, under "Report a bug 🙋‍♂️ Request feature" for the simple fact that clicking where you are currently would take you back to the right place.

Current result:
Clicking on "Live Version Here" jumps to the top because the page starts with "Live Version Here".

Expected result:
That when clicking on "Live Version Here" it jumps down according to the title that is clicked.

Screen size:
Full screen.

Screenshots:
![image](https://user-images.githubusercontent.com/74306449/167274904-2946bb05-4595-4b06-be14-af2e5e57db03.png)

![image](https://user-images.githubusercontent.com/74306449/167274934-1df5fc70-0673-4bf0-8185-fcb348b42101.png)

Check list:
This issue can be closed when the following tasks are completed:
-That the indicated error be modified.
References:
https://github.com/Israel-Laguan/credit-card-component#readme

Spanish Version:

**Explicación:**

La tabla de contenido debe estar al principio, debajo de "Informar un error 🙋‍♂️ Solicitar función" por el simple hecho de que al hacer clic en el lugar en el que te encuentras, volverás al lugar correcto.

resultado actual:
Al hacer clic en "Versión en vivo aquí" salta a la parte superior porque la página comienza con "Versión en vivo aquí".

Resultado Esperado:
Que al hacer clic en "Versión en vivo aquí" salta hacia abajo según el título que se haga clic.

Tamaño de pantalla:
Pantalla completa.

Capturas de pantalla:
![imagen](https://user-images.githubusercontent.com/74306449/167274904-2946bb05-4595-4b06-be14-af2e5e57db03.png)

![imagen](https://user-images.githubusercontent.com/74306449/167274934-1df5fc70-0673-4bf0-8185-fcb348b42101.png)

Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
-Que se modifique el error indicado.
Referencias:
https://github.com/Israel-Laguan/credit-card-component#readme

**Comment by Eghinner** [comment]
I want to take it

**Comment by heliomar-pena** [comment]
@Eghinner now you're assigned
