### ISSUE TITLE
Table Of Contents(Tip) In Credit Card Component  /  Tabla De Contenido (Consejo) En El Componente De Tarjeta De Crédito

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#137]
**Explanation:**

The table of contents should not be self-contained, as a suggestion and practicality to find the topic you want, if it would look good from the topic you are standing on, have an item that leads directly to the table of contents to reselect a topic.

Current result:
When you get to the table of contents, you can see that there is a topic called table of contents and when you click, it shows the same screen.

Expected result:
That when reaching the table of contents there is no point called table of contents.

Screen size:
Full screen.

Screenshots:
![image](https://user-images.githubusercontent.com/74306449/167275296-70cc7e5a-433c-4739-b5ca-2c3c44c81881.png)
![image](https://user-images.githubusercontent.com/74306449/167275360-29a304ba-6f5d-42a6-8967-5701e7becb31.png)

Check list:
This issue can be closed when the following tasks are completed:
-That the indicated error be modified.

References:
https://github.com/Israel-Laguan/credit-card-component#npm-start
https://github.com/Israel-Laguan/guimy-backend#table-of-contents

Spanish Version:

**Explicación:**

La tabla de contenido no debe ser independiente, como una sugerencia y practicidad para encontrar el tema que desea, si se vería bien desde el tema en el que se encuentra, tenga un elemento que lleve directamente a la tabla de contenido para volver a seleccionar un tema.

resultado actual:
Cuando llega a la tabla de contenido, puede ver que hay un tema llamado tabla de contenido y cuando hace clic, muestra la misma pantalla.

Resultado Esperado:
Que al llegar a la tabla de contenido no haya un punto llamado tabla de contenido.

Tamaño de pantalla:
Pantalla completa.

Capturas de pantalla:
![imagen](https://user-images.githubusercontent.com/74306449/167275296-70cc7e5a-433c-4739-b5ca-2c3c44c81881.png)
![imagen](https://user-images.githubusercontent.com/74306449/167275360-29a304ba-6f5d-42a6-8967-5701e7becb31.png)

Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
-Que se modifique el error indicado.

Referencias:
https://github.com/Israel-Laguan/credit-card-component#npm-start
https://github.com/Israel-Laguan/guimy-backend#table-of-contents

**Comment by Eghinner** [comment]
I want to take it

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171165810-b4207d79-f113-44d3-9542-69626b723ce5.png)
