### ISSUE TITLE
Error when entering "Collaborators"

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#138]
Explanation
In the option "Collaborators" it indicates "3", but when entering it shows the page but does not load the information.

Current result:
When entering Collaborators, it shows the page but does not load the information.

Expected result:
That when entering Collaborators, show the page and load the information.

Screen size:
all screens

Screenshots
![image](https://user-images.githubusercontent.com/74306449/167277825-d75d83ce-e445-4285-b3a6-4ed5bb0673dd.png)

Check list
This issue can be closed when the following tasks are completed:
-That the indicated error be modified.

References
https://github.com/Israel-Laguan/React-SaaS-E-Commerce-Starter
https://github.com/Israel-Laguan/credit-card-component
https://github.com/Israel-Laguan/Shopeasy
https://github.com/Israel-Laguan/proximity-post-it
https://github.com/Israel-Laguan/guimy-backend/graphs/contributors

**Comment by Israel-Laguan** [comment]
This is a bug from Github, so this is invalid
