### ISSUE TITLE
Missing Percentage Chart - Home 

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#14]
### Explanation:

Missing percentage box.

*Screen size:* (in all resolutions )

### Screenshots:

Original: (![image](https://user-images.githubusercontent.com/4030477/160701192-0d4b37a4-29df-4a96-8771-4e8c9466d517.png))
Our: (![image](https://user-images.githubusercontent.com/4030477/160701145-33bf3b54-a1ff-4467-aa9a-92d9053ae494.png))

### References:
 
Original: http://spgatsbystg.wpengine.com/
Our: https://wwwsimplepracticegatsbystaging.gtsb.io/

**Comment by denisosuna** [comment]
Fixed in:
https://github.com/simplepractice/www-simplepractice-gatsby/pull/new/fix/home-practitioner-satisfaction-div

**Comment by heliomar-pena** [comment]
@denisosuna Good work!
