### ISSUE TITLE
Change Image -  Restaurant-Page  /  Cambiar Imagen - Página Del Restaurante

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#141]
### Explanation:

It is recommended to change the image for one more in line with the page, so that the user when viewing the image understands the content of the page.

**Actual result:** The image does not match the content of the page.

**Expected result:** That there is an image according to the content of the page.

*Screen size:* The whole screen.

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167278572-b08399bf-5ab1-47ab-8244-03cdb688ef4d.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] When there is an image that when you look at it you can understand what the page is about.### Explanation:

It is recommended to change the image for one more in line with the page, so that the user when viewing the image understands the content of the page.

**Actual result:** The image does not match the content of the page.

**Expected result:** That there is an image according to the content of the page.

*Screen size:* The whole screen.

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167278572-b08399bf-5ab1-47ab-8244-03cdb688ef4d.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] When there is an image that when you look at it you can understand what the page is about.

### References:
Our: https://github.com/Israel-Laguan/Restaurant-Page

Spanish Version:

### Explicación:

Se recomienda cambiar la imagen por una más acorde con la página, para que el usuario al visualizar la imagen entienda el contenido de la página.

**Resultado real:** La imagen no coincide con el contenido de la página.

**Resultado esperado:** Que haya una imagen acorde al contenido de la página.

*Tamaño de pantalla:* Pantalla completa.

### Capturas de pantalla:
Nuestra:
![imagen](https://user-images.githubusercontent.com/103531307/167278572-b08399bf-5ab1-47ab-8244-03cdb688ef4d.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Que haya una imagen que cuando la mires puedas entender de qué trata la página.

### Referencias:
Nuestra: https://github.com/Israel-Laguan/Restaurant-Page

**Comment by mdrianislam0or1** [comment]
Changed Image with the content.


![fix](https://user-images.githubusercontent.com/67714964/168484001-db040a26-204a-4d58-be33-60c923b275c2.jpg)

**Comment by heliomar-pena** [comment]
@Israel-Laguan @angelik0828 What do you think about the image?

**Comment by heliomar-pena** [comment]
> Changed Image with the content.
> 
> ![fix](https://user-images.githubusercontent.com/67714964/168484001-db040a26-204a-4d58-be33-60c923b275c2.jpg)

@mdrianislam0or1 
Could you remove the background? You can use this online tool: https://www.remove.bg/ just uplaod the image and click on "Remove BG"

**Comment by Israel-Laguan** [comment]
> @Israel-Laguan @angelik0828 What do you think about the image?

I think @angelik0828 should confirm, I am ok with that one

**Comment by angelik0828** [comment]
I think it may have the white background.

**Comment by Israel-Laguan** [comment]
> I think it may have the white background.

Maybe you meant Transparent background?

**Comment by angelik0828** [comment]
yes I meant , I think it would look better without the white background

**Comment by mdrianislam0or1** [comment]
Ok

**Comment by mdrianislam0or1** [comment]
![rm](https://user-images.githubusercontent.com/67714964/169435744-7b694104-49be-45f5-b16b-df9c28587943.jpg)

**Comment by angelik0828** [comment]
Everything has been checked!

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171165557-b9e2224f-5ec8-4c0b-b152-f41f964e9569.png)
