### ISSUE TITLE
   Redirect Error When Clicking "Tools"  /   Error De Redireccionamiento Al Hacer Clic En "Herramientas"

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#142]
Explanation:

 In "My Favorite Tools", clicking each of the links does not take you to the correct page.

Current result:
Entering "My Favorite Tools" and clicking on a link does not display the corresponding page.

Expected result:
That when entering "My favorite tools" and clicking on a link, it shows the page that corresponds to it.

Screen size:
Full size.

Screenshots:

![image](https://user-images.githubusercontent.com/74306449/167725776-6de76e3e-061a-43cf-8afd-aaa3de2b09a9.png)
![image](https://user-images.githubusercontent.com/74306449/167729698-150fcd8d-060d-4a44-a8e2-c9d869932d9c.png)

Check list:
This issue can be closed when the following tasks are completed:
-That each of the links are verified and shows the correct result.

References:
https://github.com/Israel-Laguan/Israel-Laguan
https://github.com/Israel-Laguan/proximity-post-it
https://github.com/Israel-Laguan/credit-card-component/
https://github.com/Israel-Laguan/Shopeasy
https://github.com/Israel-Laguan/arduino-relay-app
https://github.com/Israel-Laguan/israel-laguan.github.io
https://github.com/Israel-Laguan/healthy-foodie
https://github.com/Israel-Laguan/movie-discover
https://github.com/Israel-Laguan/guimy-backend

Spanish Version:

En "Mis herramientas favoritas", hacer clic en cada uno de los enlaces no lo lleva a la página correcta.

Resultado actual:
Entrar en "Mis herramientas favoritas" y hacer clic en un enlace no muestra la página correspondiente.

Resultado Esperado:
Que al entrar en "Mis herramientas favoritas" y hacer clic en un enlace, muestra la página que le corresponde.

Tamaño de pantalla:
Pantalla completa.

Capturas de pantalla:

![imagen](https://user-images.githubusercontent.com/74306449/167725776-6de76e3e-061a-43cf-8afd-aaa3de2b09a9.png)
![imagen](https://user-images.githubusercontent.com/74306449/167729698-150fcd8d-060d-4a44-a8e2-c9d869932d9c.png)

Lista de Verificación:
Este problema se puede cerrar cuando se completan las siguientes tareas:
-Que cada uno de los enlaces estén verificados y muestre el resultado correcto.

Referencias:
https://github.com/Israel-Laguan/Israel-Laguan
https://github.com/Israel-Laguan/proximity-post-it
https://github.com/Israel-Laguan/credit-card-component/
https://github.com/Israel-Laguan/Shopeasy
https://github.com/Israel-Laguan/arduino-relay-app
https://github.com/Israel-Laguan/israel-laguan.github.io
https://github.com/Israel-Laguan/healthy-foodie
https://github.com/Israel-Laguan/movie-descubrir
https://github.com/Israel-Laguan/guimy-backend

**Comment by Israel-Laguan** [comment]
I think those are not intended to be links. I can propose to change to links to the pages for each project

**Comment by anaPiris** [comment]
Thanks Irsael, that's what I asked Angelica to see if she really should redirect

**Comment by Israel-Laguan** [comment]
They can redirect, but to the tools webpage, @e-azocar or @angelik0828 can check which are those pages

**Comment by e-azocar** [comment]
Those tools are Javascript, React, Node, PostgreSQL, items like these. I think they can redirect to the documentation of each one of them

**Comment by mdrianislam0or1** [comment]
https://github.com/Israel-Laguan/Israel-Laguan/pull/3
https://github.com/Israel-Laguan/proximity-post-it/pull/82
https://github.com/Israel-Laguan/credit-card-component/pull/18
https://github.com/Israel-Laguan/Shopeasy/pull/14
https://github.com/Israel-Laguan/arduino-relay-app/pull/24
https://github.com/Israel-Laguan/israel-laguan.github.io/pull/4
https://github.com/Israel-Laguan/healthy-foodie/pull/6
https://github.com/Israel-Laguan/movie-discover/pull/12
https://github.com/Israel-Laguan/guimy-backend/pull/1

**Comment by Israel-Laguan** [comment]
> [Israel-Laguan/Israel-Laguan#3](https://github.com/Israel-Laguan/Israel-Laguan/pull/3) [Israel-Laguan/proximity-post-it#82](https://github.com/Israel-Laguan/proximity-post-it/pull/82) [Israel-Laguan/credit-card-component#18](https://github.com/Israel-Laguan/credit-card-component/pull/18) [Israel-Laguan/Shopeasy#14](https://github.com/Israel-Laguan/Shopeasy/pull/14) [Israel-Laguan/arduino-relay-app#24](https://github.com/Israel-Laguan/arduino-relay-app/pull/24) [Israel-Laguan/israel-laguan.github.io#4](https://github.com/Israel-Laguan/israel-laguan.github.io/pull/4) [Israel-Laguan/healthy-foodie#6](https://github.com/Israel-Laguan/healthy-foodie/pull/6) [Israel-Laguan/movie-discover#12](https://github.com/Israel-Laguan/movie-discover/pull/12) [Israel-Laguan/guimy-backend#1](https://github.com/Israel-Laguan/guimy-backend/pull/1)

@anaPiris @angelik0828 please check

**Comment by angelik0828** [comment]
Everything has been checked!
