### ISSUE TITLE
Fix Link Error - Restaurant-Page  /  Solucionar Error De Enlace - Página De Restaurante

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#143]
### Explanation:

It is recommended to correct the link error since clicking does not open.

**Current result:** Clicking on the link shows an error on the page.

**Expected result:** Open to the next page when you click.

*Screen size:* The whole screen 

### Screenshots:

Our: 
![image](https://user-images.githubusercontent.com/103531307/167278749-b185f0d2-0360-427f-a15a-6f84bec8a1df.png)

### Checklist:

This issue can be closed when the following tasks are completed:
 
 - [ ] When clicking on the link opens.

### References:

Our: https://github.com/Israel-Laguan/Restaurant-Page

Spanish Version:

### Explicación:

Se recomienda corregir el error del enlace ya que al hacer click no  abre.

**Resultado actual:**Al hacer clic en el enlace muestra un error en la página.

**Resultado esperado:** Abrir en la página siguiente al hacer clic.

*Tamaño de pantalla:* Pantalla completa.

### Capturas de pantalla:

Nuestras:
![imagen](https://user-images.githubusercontent.com/103531307/167278749-b185f0d2-0360-427f-a15a-6f84bec8a1df.png)

### Lista de Verificación:

Este problema se puede cerrar cuando se completan las siguientes tareas:
 
 - [ ] Al hacer clic en el enlace se abre.

### Referencias:

Nuestro: https://github.com/Israel-Laguan/Restaurant-Page

**Comment by e-azocar** [comment]
That link is only for documentation, so, I think isn't necessary change it
