### ISSUE TITLE
Add description link - Codes-Biblion

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#145]
### Explanation
It is recommended to add a content link, it is also recommended to remove the Releases and Packages since they do not have published content.

**Actual result:** There is no content link, Releases and Packages have no published content.

**Expected result:** That there is a content link, that the Releases and Packages are eliminated since they do not have published content.

*Screen size:* all screen

### Screenshots

Our: 
![image](https://user-images.githubusercontent.com/103531307/167278967-cdaf90e8-5b62-416c-85d4-e58957a02f22.png)

### Checklist
This issue can be closed when the following tasks are complete:
 
 - [ ] When there is content link.
 - [ ] When Releases and Packages are removed.

### References

Our: https://github.com/Israel-Laguan/Codes-Biblion

**Comment by Israel-Laguan** [comment]
This one don't need a link as is not a page to be deployed
