### ISSUE TITLE
Check That The Repository Name In The Tag Is Correct  /  Verifique Que El Nombre Del Repositorio En La etiqueta Sea Correcto

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#146]
Explanation:

When clicking on the Issues-Open/Closed label, it should show only the issues that have been opened/closed, as appropriate, but it shows information that does not correspond to the one selected.
The solution would be to check that the repository name in the tag is correct.

Current result:
Clicking on the Open or /Closed Issues tag does not display the correct information.

Expected result:
 Clicking on the Open or Closed Issues label displays the correct information.
 
Screen size:
Full screen.

Screenshots:

![image](https://user-images.githubusercontent.com/74306449/168695476-02bfe550-732e-4944-ab68-a9083ead2ed3.png)
![image](https://user-images.githubusercontent.com/74306449/168695514-48da4813-2a5b-433c-a6d7-37d587528071.png)

![image](https://user-images.githubusercontent.com/74306449/168694938-cb1d4d2b-22cf-47bf-a25d-daaed089cf2b.png)
![image](https://user-images.githubusercontent.com/74306449/168695248-7acce664-282c-4b81-b372-713f8220c6b7.png)

Checklist:
This issue can be closed when the following tasks are completed:

-Check that when you click on the tag, you are redirected to the repository corresponding to it.

References:

https://github.com/Israel-Laguan/healthy-foodie
https://github.com/Israel-Laguan/arduino-relay
https://github.com/Israel-Laguan/healthy-foodie
https://github.com/Israel-Laguan/movie-discover
https://github.com/Israel-Laguan/Tic-Tac-Toe/issues
https://github.com/Israel-Laguan/express-server-jwt
https://github.com/Israel-Laguan/FaircoinRPS
https://github.com/Israel-Laguan/textedit-app
https://github.com/Israel-Laguan/yjs-react-exam
https://github.com/Israel-Laguan/microverse-trial-4
https://github.com/Israel-Laguan/microverse-trial-3

Spanish Version:

Explicación:

Al hacer clic en la pestaña Incidencias-Abrir/Cerrar, solo se deben mostrar las incidencias que se han abierto/cerrado, según corresponda, pero muestra información que no corresponde a la seleccionada.
La solución sería verificar que el nombre del repositorio en la etiqueta sea correcto.

Resultado actual:
Hacer clic en la etiqueta Problemas abiertos o cerrados no muestra la información correcta.

Resultado Esperado:
 Al hacer clic en la etiqueta Problemas abiertos o cerrados, se muestra la información correcta.
 
Tamaño de pantalla:
Pantalla completa.

Capturas de pantalla:

![imagen](https://user-images.githubusercontent.com/74306449/168695476-02bfe550-732e-4944-ab68-a9083ead2ed3.png)
![imagen](https://user-images.githubusercontent.com/74306449/168695514-48da4813-2a5b-433c-a6d7-37d587528071.png)

![imagen](https://user-images.githubusercontent.com/74306449/168694938-cb1d4d2b-22cf-47bf-a25d-daaed089cf2b.png)
![imagen](https://user-images.githubusercontent.com/74306449/168695248-7acce664-282c-4b81-b372-713f8220c6b7.png)

Lista de Verificación:
Este problema se puede cerrar cuando se completan las siguientes tareas:

-Comprueba que al hacer clic en la etiqueta, eres redirigido al repositorio correspondiente a la misma.

Referencias:

https://github.com/Israel-Laguan/healthy-foodie
https://github.com/Israel-Laguan/arduino-relé
https://github.com/Israel-Laguan/healthy-foodie
https://github.com/Israel-Laguan/movie-descubrir
https://github.com/Israel-Laguan/Tic-Tac-Toe/issues
https://github.com/Israel-Laguan/express-server-jwt
https://github.com/Israel-Laguan/FaircoinRPS
https://github.com/Israel-Laguan/textedit-app
https://github.com/Israel-Laguan/yjs-react-examen
https://github.com/Israel-Laguan/microverse-trial-4
https://github.com/Israel-Laguan/microverse-trial-3

**Comment by Israel-Laguan** [comment]
This description is not accurate @anaPiris 

About the incorrect data, you are right

**Comment by Israel-Laguan** [comment]
Solution would be to check the name of the repository on the label is correct, maybe is pointing to another repo

**Comment by Eghinner** [comment]
I made the possible changes. The other repositories do not have issues enabled.

**Comment by angelik0828** [comment]
Everything has been checked!
