### ISSUE TITLE
Remove Asterisks - Codes-Biblion  /  Eliminar Asteriscos - Codes-Biblion

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#147]
### Explanation:

It is recommended to remove asterisks at the beginning of the styles, this to make it look better.

**Current result:** Asterisks to the left of styles.

**Expected result:** There are no asterisks in that part of the presentation.

*Screen size:* The whole screen. 

### Screenshots:

Our: 
![image](https://user-images.githubusercontent.com/103531307/167279169-318ac0c5-a432-468a-a82b-dab67e76d858.png)

### Checklist:

This issue can be closed when the following tasks are completed:
 
 - [x] When there are no asterisks in that part of the presentation.

### References:

Ours: https://github.com/Israel-Laguan/Codes-Biblion

Spanish Version:

### Explicación:

Se recomienda quitar los asteriscos al inicio de los estilos, esto para que se vea mejor.

**Resultado actual:
** Asteriscos a la izquierda de los estilos.

**Resultado esperado:
** No hay asteriscos en esa parte de la presentación.

*Tamaño de pantalla:* Pantalla completa.

### Capturas de pantalla:

Nuestra:
![imagen](https://user-images.githubusercontent.com/103531307/167279169-318ac0c5-a432-468a-a82b-dab67e76d858.png)

### Lista de Verificación:

Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [x] Cuando no hay asteriscos en esa parte de la pantalla.

### Referencias:

Nuestras: https://github.com/Israel-Laguan/Codes-Biblion

**Comment by Coolhatena** [comment]
Done, i already sent the pull request to solve the issue  -Eduardo Rivera

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171157256-fb5f284a-7f2c-4427-bb57-c1abe9a89c70.png)
