### ISSUE TITLE
Unwrapped Text -Home

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#15]
### Explanation:

In the blue bar, where the stars are on the different screens, the text is not organized.

*Screen size:* (320X532 , 375X532, 768X532,  )

### Screenshots

Original: 
![image](https://user-images.githubusercontent.com/4030477/160705879-0888eb8a-fed1-4caf-8536-8cb1cfcfebbc.png)
![image](https://user-images.githubusercontent.com/4030477/160706611-c8050448-c376-45f5-9cfd-f4602122b717.png)
![image](https://user-images.githubusercontent.com/4030477/160708379-e510770d-a476-44dd-9d4e-dfb5e8f53022.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/160705924-546453dd-96fb-4f71-ad6b-7c7ab38ab6af.png)
![image](https://user-images.githubusercontent.com/4030477/160708700-1837b2fc-b6b4-415b-abf9-014cfb6e5258.png)
![image](https://user-images.githubusercontent.com/4030477/160708605-bbd117a7-a283-4326-87f9-392635122d96.png)

### Checklist

 - [ ] Adjust resolutions.
 - [ ] Review screens.
 
### References:

Original: https://spgatsbystg.wpengine.com/
Our: https://wwwsimplepracticegatsbystaging-fixcapterrabannertextstyle.gtsb.io/

**Comment by arodriguezl9302** [comment]
I would like to be assigned to this task @Katsu08

**Comment by heliomar-pena** [comment]
I don't see the problem @angelik0828 Can you check please?

[Gatsby](https://wwwsimplepracticegatsbystaging.gtsb.io/)
[Original](https://spgatsbystg.wpengine.com/)

**Comment by angelik0828** [comment]
revised!! All Right
