### ISSUE TITLE
Change Styles - MathMagicians-Calculator  /  Cambiar Estilos - MathMagicians-Calculator

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#151]
### Explanation:

It is recommended to switch to larger styles to make it look better presented visually.

**Current result:** The styles are very small.

**Expected result:** Let the styles be larger.

*Screen size:* The whole screen 

### Screenshots:

Our: 
![image](https://user-images.githubusercontent.com/103531307/167443315-6175b936-b0de-4106-9397-f18ee0693a7a.png)

### Checklist:

This issue can be closed when the following tasks are completed:
 
 - [ ] When the styles are bigger.

### References:

Our: https://github.com/Israel-Laguan/MathMagicians-Calculator

Spanish Version:

### Explicación:

Se recomienda cambiar a estilos más grandes para que se vea mejor presentado visualmente.

**Resultado actual:** Los estilos son demasiado pequeños.

**Resultado esperado:** Hacer los estilos más grandes.

*Tamaño de pantalla:* Pantalla completa

### Capturas de pantalla:

Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167443315-6175b936-b0de-4106-9397-f18ee0693a7a.png)

### Lista de Verificación:

Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Cuando los estilos son más grandes.

### Referencias:

Nuestro: https://github.com/Israel-Laguan/MathMagicians-Calculator

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171162249-5bb09dea-1ec5-49d7-81c4-405b6eb34e90.png)
