### ISSUE TITLE
Change Image - MathMagicians-Calculator  /  Cambiar Imagen - MathMagicians-Calculator

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#152]
### Explanation:

It is recommended to change the image for one more in line with the content of the page.

**Current result:** Image does not match the content.

**Expected result:** That there is an image according to the content.

*Screen size:* Full screen. 

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167445707-40a22a90-853e-41d7-973a-f10e9ac9519e.png)

### Checklist:

This issue can be closed when the following tasks are completed:
 
 - [ ] When there is an image according to the content.

### References:

Our: https://github.com/Israel-Laguan/MathMagicians-Calculator

Spanish Version:

### Explicación:

Se recomienda cambiar la imagen por una más acorde con el contenido de la página.

**Resultado actual:
** La imagen no coincide con el contenido.

**Resultado esperado:** Que haya una imagen acorde al contenido.

*Tamaño de pantalla:* Pantalla completa.

### Capturas de pantalla:

Nuestra:
![imagen](https://user-images.githubusercontent.com/103531307/167445707-40a22a90-853e-41d7-973a-f10e9ac9519e.png)

### Lista de Verificación:

Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Cuando haya una imagen acorde al contenido.

### Referencias:
Nuestro: https://github.com/Israel-Laguan/MathMagicians-Calculator

**Comment by Israel-Laguan** [comment]
@angelik0828 in this case what image you propose?

**Comment by angelik0828** [comment]
it could be something like that
![imagen](https://user-images.githubusercontent.com/4030477/167905004-9c3307d4-be24-4774-ad58-545da2da65b7.svg)

**Comment by mdrianislam0or1** [comment]
I created a pull request on that project.

**Comment by mdrianislam0or1** [comment]
https://github.com/Israel-Laguan/MathMagicians-Calculator/pull/17

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171162072-3d1380eb-6ab3-436b-9841-a65c3302eb90.png)
