### ISSUE TITLE
Link Error -  MathMagicians-Calculator  /   Error En El Enlace - MathMagicians-Calculator

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#153]
### Explanation:

It is recommended to correct the bug in the link since it does not open when clic.
### Explanation:
The link is invalid.

**Current result:** The link does not work.

**Expected result:** Make the link open when  clicking.

*Screen size:* Full screen. 

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167450463-10452489-ecb2-44b5-b903-a7ec7b952c4f.png)

### Checklist:

This issue can be closed when the following tasks are completed:
 
 - [ ] When the link works correctly.

### References:

Our: https://github.com/Israel-Laguan/MathMagicians-Calculator

Spanish Version:

### Explicación:

Se recomienda corregir el error en el enlace ya que no abre al hacer click.
### Explicación:.
El enlace es inválido.
**Resultado actual:** El enlace no funciona.

**Resultado esperado:** Hacer que el enlace se abra al hacer clic.

*Tamaño de pantalla:* Pantalla completa. 

### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167450463-10452489-ecb2-44b5-b903-a7ec7b952c4f.png)

### Lista de Verificación:

Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Cuando el enlace funciona correctamente.

### Referencias:
Nuestro: https://github.com/Israel-Laguan/MathMagicians-Calculator

**Comment by e-azocar** [comment]
That link is only for documentation, so, I think isn't necessary change it

**Comment by angelik0828** [comment]
https://github.com/Israel-Laguan/MathMagicians-Calculator/pull/18#pullrequestreview-990270416
**
![image](https://user-images.githubusercontent.com/4030477/171161836-cb3474d4-c666-46f9-9920-01efacef3716.png)
**
