### ISSUE TITLE
Add Link -  Library  /  Añadir Enlace -Library

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#154]
### Explanation:

Implement code so that it can be a link on the content to put in About.

**Current result:** there is no implemented code to put in About, Releases and packages have no published content.

**Expected result:** That there is code implemented that is a link in the content in About, that there are no Releases and packages since they do not have published content.

*Screen size:* Full screen

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167457532-20acd636-2171-4999-8053-adc9d7119cea.png)

### Checklist:

This issue can be closed when the following tasks are completed:
 
 - [ ] when code is implemented that can be a link on the content to put in About.
 - [ ] When there are no Releases and Packages.

### References:
Our: https://github.com/Israel-Laguan/library

-----------------------------------------------------------------

Spanish Version:

### Explicación:

Implemente código para que pueda ser un enlace en el contenido para poner en Acerca de.

**Resultado actual:** no hay ningún código implementado para poner Acerca de, las versiones y los paquetes no tienen contenido publicado.

**Resultado esperado:** Que haya código implementado que sea un link en el contenido en Acerca de, que no haya Lanzamientos y Paquetes ya que no tienen contenido publicado.

*Tamaño de pantalla:*  
Pantalla completa.

### Capturas de pantalla:
Nuestra:
![imagen](https://user-images.githubusercontent.com/103531307/167457532-20acd636-2171-4999-8053-adc9d7119cea.png)

### Lista de Verificación:

Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [x] Cuando se implementa un código que puede ser un enlace en el contenido para poner en "Acerca de".
 - [x] #187

### Referencias:

Nuestra: https://github.com/Israel-Laguan/library

**Comment by Israel-Laguan** [comment]
Please modify text to something like "Deploy code so it can be a link to put on About", as the real solution here is to deploy

**Comment by roberto-97c** [comment]
Taking into account the suggestions, the text was modified, Thank you.

**Comment by angelik0828** [comment]
@AdrianFagilde Can this be checked now?

**Comment by AdrianFagilde** [comment]
I have not done it yet, this week I will solve it.

**Comment by AdrianFagilde** [comment]
@Israel-Laguan  Good night, Mr. Israel, only you can make this changes in your repository, to be able to solve this tasks.

In the images are the steps to make all the changes you requested in the task.
![image](https://user-images.githubusercontent.com/65044786/171318807-b10d79c8-ce08-4264-b1b8-36a4df9428c1.png)
![image](https://user-images.githubusercontent.com/65044786/171318913-ff1b0db7-f776-4c9d-8bae-4cc0a25386ab.png)

**Comment by Israel-Laguan** [comment]
@AdrianFagilde Ah sorry for the misunderstanding, the task here is to deploy this site. Notice is only an HTML. What do you think of using gh-pages to deploy it?

**Comment by AdrianFagilde** [comment]
@Israel-Laguan  Hello, yes it seems to me the best option, I am going to do the deploy tonight with gh-pages

**Comment by angelik0828** [comment]
fixed!!
