### ISSUE TITLE
Change Image -  Library  /  Cambiar Imagen - Biblioteca

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#155]
### Explanation:

It is recommended to change the image for another more related to the content.

**Current result:** The published image is not related to the content.

**Expected result:** That the image is related to the content.

*Screen size:* Full screen.
### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167462631-8b2d5320-d07f-44a3-ba7c-7ffeb12c51a2.png)

### Checklist:

This issue can be closed when the following tasks are completed:
 
 - [ ] When there is another image that is related to the content.
 
### References:
Our: https://github.com/Israel-Laguan/library

Spanish Version:

### Explicación:

Se recomienda cambiar la imagen por otra más relacionada con el contenido.

**Resultado actual:
** La imagen publicada no está relacionada con el contenido.

**Resultado esperado:
** Que la imagen tenga relación con el contenido.

*Tamaño de pantalla:* Pantalla completa.

### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167462631-8b2d5320-d07f-44a3-ba7c-7ffeb12c51a2.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completan las siguientes tareas:
 
 - [ ] Cuando hay otra imagen que tiene relación con el contenido.
### Referencias:

Nuestro: https://github.com/Israel-Laguan/library

**Comment by Israel-Laguan** [comment]
@angelik0828 what image you can propose?

**Comment by angelik0828** [comment]
We could see it, make an image referring to a bookstore

**Comment by mdrianislam0or1** [comment]
Changed image related to the content.


![fix](https://user-images.githubusercontent.com/67714964/168573478-259af342-0ffe-4f81-8970-b24fec0d4d68.jpg)

**Comment by mdrianislam0or1** [comment]
https://github.com/Israel-Laguan/library/pull/2

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171161223-b967d5f9-ae08-43a5-a78a-b306ebb6022b.png)
