### ISSUE TITLE
Change Styles - Irla-Facebook  /  Cambiar Estilos - Irla-Facebook

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#157]
### Explanation:
The styles are very small, it is recommended to exchange them for larger styles.

**Current result:** The styles are very small.

**Expected result:** Make the styles bigger.

*Screen size:* Full screen.

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167476691-b4cc4f51-eeb5-4754-80e0-f67e9d46c215.png)

### Checklist:

This issue can be closed when the following tasks are completed:
  - [ ] When styles have been resized to a larger size.
### References:

Our: https://github.com/Israel-Laguan/irla-facebook#readme

Spanish Version:

### Explicación:

Los estilos son muy pequeños, se recomienda cambiarlos por estilos más grandes.

**Resultado actual:** Los estilos son demasiado pequeños.

**Resultado esperado:** Hacer los estilos más grandes.

*Tamaño de pantalla:* Pantalla completa.

### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167476691-b4cc4f51-eeb5-4754-80e0-f67e9d46c215.png)

### Lista de Verificación:

Este problema se puede cerrar cuando se completen las siguientes tareas:
 - [ ] Cuando los estilos se han redimensionado a un tamaño mayor.

 ### Referencias:
Nuestro: https://github.com/Israel-Laguan/irla-facebook#readme

**Comment by mdibuhossain** [comment]
I created a [pull request](https://github.com/Israel-Laguan/irla-facebook/pull/3)

![image](https://user-images.githubusercontent.com/59278819/169150354-16c54d51-bd12-478c-ab71-55a6dc5b1a62.png)

Is that ok?

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171161061-b7e5506e-c029-42cc-8bea-53cbececc7a9.png)
