### ISSUE TITLE
Blurred images

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#158]
### Explanation
When entering the page "overtime-app/desired state" the images are not clear and it is not legible.

**Actual result:**
When entering the page reaching "desired state" the images are not clear and the letter is not legible.

**Expected result:**
That when entering the page reaching "desired state" the images are clear and the letter legible.

*Screen size:*
all screens

### Screenshots
![image](https://user-images.githubusercontent.com/74306449/167516471-7ed4d375-689f-44eb-b053-c61de5fbf977.png)
![image](https://user-images.githubusercontent.com/74306449/167516493-52427f14-33eb-4684-b150-837362ee05ea.png)

### Check list
   This issue can be closed when the following tasks are completed:
   -when the identified images are corrected.
 
### References

https://github.com/Israel-Laguan/overtime-app

**Comment by Israel-Laguan** [comment]
In this case the source was like that, so this is invalid
