### ISSUE TITLE
   Page Header Or Title At The Top Of The Page

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#159]
### Explanation:

When entering the page "overtime-app/ at the top of the page there is no start equal to the other pages, which makes it look like a page off, it lacks images and color at the beginning.

**Actual result:**
When entering the page there is no header with images and/or color as in the other pages.

**Expected result:**

That when entering the page at the beginning, a header with images and/or color similar to the other pages is observed.

*Screen size:*
The whole screen.

### Screenshots:

![image](https://user-images.githubusercontent.com/74306449/167521039-7414aa31-761d-4ee1-b33c-acbdc1b071b7.png)

### Check list:

This issue can be closed when the following tasks are completed:
-If the suggestion is approved, the beginning of it should look the same as the other pages.
 
### References:
https://github.com/Israel-Laguan/overtime-app

**Comment by mdrianislam0or1** [comment]
Any recommended image for this project?

**Comment by angelik0828** [comment]
this is already solved
