### ISSUE TITLE
Scroll More Card - Features /Updates

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#16]
### Explanation:

At the top of the page between the blue and white section, Scroll More card on this icon is not the same color and size as the original, the icon is not aligned with the text.

*Screen size:* (all resolutions )

### Screenshots

Original: ![image](https://user-images.githubusercontent.com/4030477/160871677-3f573e44-e7e1-411c-929e-b5f901912c98.png)
![image](https://user-images.githubusercontent.com/4030477/160877922-57d86b47-7a03-4768-a20d-c37b37ac859e.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/160871635-4ad2704e-2e9b-4b80-a5ca-482e58aedf49.png)
![image](https://user-images.githubusercontent.com/4030477/160877835-f59d4fd3-5d51-45b5-8573-7c7c152a2552.png)

### Checklist
 
 - [x] Check color.
 - [x] Check size.
 - [x] Check position.
 
### References:

Original: http://spgatsbystg.wpengine.com/features/updates/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/updates/

**Comment by heliomar-pena** [comment]
I'm working that task in pull request 391

**Comment by heliomar-pena** [comment]
Please help me to check this in this link 

Our: https://wwwsimplepracticegatsbystaging-fixscrollmorecardstyles.gtsb.io/features/updates/

Test: http://spgatsbystg.wpengine.com/features/updates/

**Comment by angelik0828** [comment]
Revised, it is already corrected!!
