### ISSUE TITLE
Link to send email

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#160]
### Explanation
When entering the page in "Author-email" clicking on email leads to another page that does not correspond to the email.

**Actual result:**
When entering the page in "Author-email", clicking on email redirects to another page that is not for email..

**Expected result:**
That when entering the page in "Author-email", clicking on email shows the page to send an email.

*Screen size:*
all screens

### Screenshots
![image](https://user-images.githubusercontent.com/74306449/167523410-9dbb719c-7641-475a-87a8-7a31a4c97353.png)
![image](https://user-images.githubusercontent.com/74306449/167523438-9e09998a-7c50-420b-8060-e3b99b1f2794.png)

### Check list
This issue can be closed when the following tasks are completed:
-It is corrected and shows the correct page.
 
### References
https://github.com/Israel-Laguan/overtime-app

**Comment by Israel-Laguan** [comment]
This will be addressed on #117
