### ISSUE TITLE
Image Does Not Match The Content - Irla-Facebook  /  La Imagen No Coincide Con El Contenido - Irla-Facebook

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#161]
### Explanation:

It is recommended to change the image for one more in line with the content.

**Current result:** Published image is not consistent with the content.

**Expected result:** That there is an image according to the content.

*Screen size:* Full screen. 

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167722011-6f53b85e-f199-4a95-bdd6-d3e0d4176d01.png)

### Checklist
This issue can be closed when the following tasks are completed:
 
 - [ ] When there is an image related to the content.

### References:
Our: https://github.com/Israel-Laguan/irla-facebook

Spanish Version:

### Explicación:

Se recomienda cambiar la imagen por una más acorde con el contenido.

**Resultado actual:** La imagen publicada no es consistente con el contenido.

**Resultado esperado:** Que haya una imagen acorde al contenido.

*Tamaño de pantalla:* Toda la pantalla.

### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167722011-6f53b85e-f199-4a95-bdd6-d3e0d4176d01.png)

### Lista de Verificación
Este problema se puede cerrar cuando se completan las siguientes tareas:
 
 - [ ] Cuando hay una imagen relacionada con el contenido.

### Referencias:
Nuestro: https://github.com/Israel-Laguan/irla-facebook

**Comment by mdrianislam0or1** [comment]
what kind of images can I use?is it about microverse?

**Comment by mdrianislam0or1** [comment]
I created a pull request in that project.

![irlaMatchImg](https://user-images.githubusercontent.com/67714964/168327565-80619fee-5738-4d96-b95a-316f31237dd7.jpg)

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171160615-7a25ceb8-f543-4025-ae41-375911eea301.png)
