### ISSUE TITLE
Add Image - Design-Your-Own-Framework  /  Agregar Imagen: Diseñe Su Propio Marco

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#163]
### Explanation:
It is recommended to add an image to the README, which is consistent with the content.

**Actual result:** There is no image in the README presentation.

**Expected result:** That there is an image that is consistent with the content.

*Screen size:* All screens. 

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167726518-5490191f-3855-4073-ae6e-3d3d7b2d2533.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] When there is an image related to the content.

### References:
Our: https://github.com/Israel-Laguan/Design-your-own-Framework

Spanish Version:

### Explicación:
Se recomienda agregar una imagen al README, que sea consistente con el contenido.

**Resultado real:** No hay imagen en la presentación README.

**Resultado esperado:** Que haya una imagen acorde al contenido.

*Tamaño de pantalla:* Todas las pantallas.

### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167726518-5490191f-3855-4073-ae6e-3d3d7b2d2533.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completan las siguientes tareas:
 
 - [ ] Cuando hay una imagen relacionada con el contenido.

### Referencias:
Nuestro: https://github.com/Israel-Laguan/Design-your-own-Framework

**Comment by Israel-Laguan** [comment]
@angelik0828 what image do you propose?

**Comment by angelik0828** [comment]
we could make an image of a grid or something similar to reference

**Comment by mdrianislam0or1** [comment]
can I add any CSS grid-type images?

**Comment by mdrianislam0or1** [comment]
I created a pull request in that project.
![pull-req](https://user-images.githubusercontent.com/67714964/168321373-a37c724f-661a-436c-ab22-ee71920d42d1.jpg)

**Comment by mdrianislam0or1** [comment]
https://github.com/Israel-Laguan/Design-your-own-Framework/pull/3

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171160348-a06c26fa-61aa-4f24-9a58-649d41e35dce.png)
