### ISSUE TITLE
Implement Image According To Content -  Design-Teardown  /  Implementar Imagen Según Contenido - Design-Teardown

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#165]
### Explanation:

It is recommended to implement an image in README that is consistent with the content and allows the user to understand at a glance what the content is about.

**Current result:**
 There is no image in README that allows to understand the content.

**Expected result:**
 There is an image implemented in README, which allows the user to understand the content.

*Screen size:*
 Full screen. 

### Screenshots:
Ours: 
![image](https://user-images.githubusercontent.com/103531307/167732337-5d085019-6eae-46cf-8163-6e92fcab97ab.png)
### Checklist:

This issue can be closed when the following tasks are completed:
 
 - [ ] When an image is implemented that allows the user to understand the content.
 
### References:
Our: https://github.com/Israel-Laguan/Design-Teardown

Spanish Version:

### Explicación:

Se recomienda implementar una imagen en README que sea consistente con el contenido y permita al usuario entender de un vistazo de qué trata el contenido.

**Resultado actual:**
 No hay imagen en README que permita entender el contenido.

**Resultado Esperado:**
 Que haya una imagen implementada en README, que permita al usuario comprender el contenido.
*Tamaño de pantalla:*
 Pantalla completa.

### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167732337-5d085019-6eae-46cf-8163-6e92fcab97ab.png)
### Lista de Verificación:

Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Cuando se implementa una imagen que permite al usuario comprender el contenido.
 
### Referencias:
Nuestro: https://github.com/Israel-Laguan/Design-Teardown

**Comment by mdrianislam0or1** [comment]
I created a pull request in that repo.

![fixtreardrown](https://user-images.githubusercontent.com/67714964/168340958-b2eb8d0a-75b7-47e0-97fd-ab89b5e3d8df.jpg)

**Comment by mdrianislam0or1** [comment]
https://github.com/Israel-Laguan/Design-Teardown/pull/4

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171160170-bf84ed00-2083-4d1e-9b08-58dcf3dda7c0.png)
