### ISSUE TITLE
Action error when clicking on an image

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#167]
### Explanation
When entering the page and clicking on the images, a redirection is made that should not occur, since this is an image that completes the content of the page.

**Actual result:**
Entering the page and clicking on an image redirects to another page.

**Expected result:**
That when entering the page and clicking on an image does not perform any action.

*Screen size:*
all screens

### Screenshots
![image](https://user-images.githubusercontent.com/74306449/167732170-2d08b5f2-a1bb-47af-842f-3b52f70d181a.png)
![image](https://user-images.githubusercontent.com/74306449/167732205-794dc250-3ce3-4a58-8d51-cd0f6893eb3b.png)
![image](https://user-images.githubusercontent.com/74306449/167732265-756088a9-6958-48a9-9e8e-683d43d3f036.png)
![image](https://user-images.githubusercontent.com/74306449/167732289-4a9e63bd-e090-43db-b916-223f98aa74bf.png)
![image](https://user-images.githubusercontent.com/74306449/167732325-25850c63-4360-41f0-8a81-01c96b1d3308.png)
![image](https://user-images.githubusercontent.com/74306449/167732361-f4068e42-1de1-435d-84e3-125232cdf01d.png)
![image](https://user-images.githubusercontent.com/74306449/167732513-9c52185b-2182-44a4-9491-7b3f023f3d09.png)
![image](https://user-images.githubusercontent.com/74306449/167733494-89492d4a-f0b5-4894-a6c0-c9ac8ba0d09c.png)
![image](https://user-images.githubusercontent.com/74306449/167734742-49e6d50c-bb66-4428-8216-df16a52af09d.png)
![image](https://user-images.githubusercontent.com/74306449/167735982-3a20075a-0e85-4ac3-a4fe-f998e54e15e4.png)
![image](https://user-images.githubusercontent.com/74306449/167736653-7f685625-c33a-465d-8d91-9d7375650c78.png)
![image](https://user-images.githubusercontent.com/74306449/167737168-4d268854-140b-40a8-8654-43b1fe0e17a1.png)
![image](https://user-images.githubusercontent.com/74306449/167737533-7f51975b-2eb3-4739-b773-a5de9742e2e2.png)
![image](https://user-images.githubusercontent.com/74306449/167737689-ebaab69a-0ad7-4f00-922b-2a97799c29fd.png)
![image](https://user-images.githubusercontent.com/74306449/167737740-8582ea02-0df9-41dd-82db-974518a77ad0.png)
![image](https://user-images.githubusercontent.com/74306449/167737916-59d75091-ae50-4b32-8f0b-babfa8966928.png)
![image](https://user-images.githubusercontent.com/74306449/167737981-7fbb6542-b844-411e-954e-b56a39286f29.png)
![image](https://user-images.githubusercontent.com/74306449/167738016-ee81c6d8-7c51-4bfb-927f-e3d4c11a4107.png)
![image](https://user-images.githubusercontent.com/74306449/167738083-cd0fcf50-fe26-49a7-93ee-6ab869357b1c.png)
![image](https://user-images.githubusercontent.com/74306449/167738191-871e6b8e-59a2-48dc-97b1-1008e3097290.png)
![image](https://user-images.githubusercontent.com/74306449/167738249-b37672fc-61c4-4ecd-8169-97270b43c345.png)
![image](https://user-images.githubusercontent.com/74306449/167738289-2bb610f7-ff37-4ae6-8dbf-7c0331d10b07.png)

### Check list
This issue can be closed when the following tasks are completed:
-The correct action is verified when clicking on all the images on each page.
 
### References
https://github.com/Israel-Laguan/proximity-post-it
https://github.com/Israel-Laguan/parrot-echo
https://github.com/Israel-Laguan/HTML-CSS-JS-Webpack-starter
https://github.com/Israel-Laguan/express-graphql-mongoose
https://github.com/Israel-Laguan/credit-card-component
https://github.com/Israel-Laguan/React-SaaS-E-Commerce-Starter
https://github.com/Israel-Laguan/Shopeasy/
https://github.com/Israel-Laguan/Advanced-Building-Blocks---Bubble-Sort
https://github.com/Israel-Laguan/israel-laguan.github.io
https://github.com/Israel-Laguan/healthy-foodie
https://github.com/Israel-Laguan/movie-discover/
https://github.com/Israel-Laguan/microverse-trial-4
https://github.com/Israel-Laguan/microverse-trial-3
https://github.com/Israel-Laguan/yjs-react-example
https://github.com/Israel-Laguan/textedit-app
https://github.com/Israel-Laguan/FaircoinRPS
https://github.com/Israel-Laguan/express-server-jwt
https://github.com/Israel-Laguan/Tic-Tac-Toe

**Comment by Israel-Laguan** [comment]
This behavior can not be changed, so its invalid

**Comment by Israel-Laguan** [comment]
It's a github thing, so we can not modify
