### ISSUE TITLE
The "MIT" Link Does Not Redirect To The Correct Page  /  El Enlace "MIT" No Redirige A La Página Correcta

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#168]
### Explanation:
Entering the page and clicking on "MIT" does not redirect to the corresponding page.

**Current result:**
Entering the page and clicking on "MIT" does not redirect to the corresponding page.

**Expected result:**
That when entering the page and clicking on "MIT" you redirect to the corresponding page.

*Screen size:*
Full screen.
### Screenshots:

![image](https://user-images.githubusercontent.com/74306449/167745116-248a0e54-dc0a-4913-abd8-cc20f8a36195.png)

![image](https://user-images.githubusercontent.com/74306449/167745142-3908150f-1ecb-47ee-bfe5-00d51f787122.png)

### Check list:

This issue can be closed when the following tasks are completed:
-The correction of the problem is verified.
 
### References:

https://github.com/Israel-Laguan/textedit-app
https://github.com/Israel-Laguan/microverse-trial-4
https://github.com/Israel-Laguan/microverse-trial-3
https://github.com/Israel-Laguan/yjs-react-example
https://github.com/Israel-Laguan/FaircoinRPS
https://github.com/Israel-Laguan/express-server-jwt

Spanish Version:

### Explicación:
Entrar en la página y hacer clic en "MIT" no redirige a la página correspondiente.

**Resultado actual:**
Entrar en la página y hacer clic en "MIT" no redirige a la página correspondiente.

**Resultado Esperado:**
Que al entrar en la página y hacer clic en "MIT" se redirija a la página correspondiente.

*Tamaño de pantalla:*
Pantalla completa.
### Capturas de pantalla:
![imagen](https://user-images.githubusercontent.com/74306449/167745116-248a0e54-dc0a-4913-abd8-cc20f8a36195.png)

![imagen](https://user-images.githubusercontent.com/74306449/167745142-3908150f-1ecb-47ee-bfe5-00d51f787122.png)

### Lista de Verificación:

Este problema se puede cerrar cuando se completen las siguientes tareas:
-Que se verifique la corrección del problema.
 
### Referencias:

https://github.com/Israel-Laguan/textedit-app
https://github.com/Israel-Laguan/microverse-trial-4
https://github.com/Israel-Laguan/microverse-trial-3
https://github.com/Israel-Laguan/yjs-react-example
https://github.com/Israel-Laguan/FaircoinRPS
https://github.com/Israel-Laguan/express-server-jwt

**Comment by Coolhatena** [comment]
I want to take this one -Eduardo Rivera

**Comment by Coolhatena** [comment]
I already sent the necessary Pull request to solve the issue

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171156168-7c10648a-af5b-4a67-89c1-4c974ea3d306.png)
