### ISSUE TITLE
The "LICENSE.md " Link Does Not Redirect To The Correct Page  /  El Enlace "LICENSE.md" No Redirige A La Página Correcta

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#169]
### Explanation:
Entering the page and clicking on "LICENSE.md" does not redirect to the corresponding page.

**Current result:**
Entering the page and clicking on "LICENSE.md" does not redirect to the corresponding page.

**Expected result:**
That when entering the page and clicking on "LICENSE.md" redirect to the corresponding page.

*Screen size:*
Full screen.

### Screenshots
![image](https://user-images.githubusercontent.com/74306449/167746067-ace50316-1249-49a8-9095-c637f0585ed7.png)
![image](https://user-images.githubusercontent.com/74306449/167746085-6d7b30cc-50c7-4ea0-8c88-95710eb88460.png)

### Check list:
This issue can be closed when the following tasks are completed:
-The correction of the problem is verified.
 
### References:
https://github.com/Israel-Laguan/Tic-Tac-Toe

Spanish Version:

### Explicación:
Entrar en la página y hacer clic en "LICENCIA.md" no redirige a la página correspondiente.

**Resultado actual:**
Entrar en la página y hacer clic en "LICENCIA.md" no redirige a la página correspondiente.

**Resultado Esperado:**
Que al ingresar a la página y hacer clic en "LICENCIA.md" redirija a la página correspondiente.

*Tamaño de pantalla:*
Pantalla completa.

### Capturas de pantalla:
![imagen](https://user-images.githubusercontent.com/74306449/167746067-ace50316-1249-49a8-9095-c637f0585ed7.png)
![imagen](https://user-images.githubusercontent.com/74306449/167746085-6d7b30cc-50c7-4ea0-8c88-95710eb88460.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
-Que se verifique la corrección del problema.
 
### Referencias:
https://github.com/Israel-Laguan/Tic-Tac-Toe

**Comment by anaceciliamolinares** [comment]
No veo las referencias.

**Comment by e-azocar** [comment]
@anaPiris please add the repository link

**Comment by Coolhatena** [comment]
I want to solve this one -Eduardo Rivera

**Comment by Coolhatena** [comment]
From what I see in the screenshot this is the repo link: https://github.com/Israel-Laguan/Tic-Tac-Toe, I already sent the necessary pull request to resolve the issue

**Comment by anaPiris** [comment]
@e-azocar disculpas, ya lo agregué.

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171155576-b9f9fda8-c164-4a89-b5a3-b9319297d76c.png)
