### ISSUE TITLE
  Space Between Text And Arrow Out Of Place - Features/Updates

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#17]
### Explanation:

Check the line spacing in the paragraph, the first line is not the same as the rest, also the arrow in front of the word "learn more" is not in place.

*Screen size:* (All resolutions ).

### Screenshots

Original: 
![image](https://user-images.githubusercontent.com/4030477/160880201-6c625b76-e5cc-4b9a-b2da-5d0c71101d79.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/160880112-1f54a5eb-c298-4522-985a-9a32764b2ddc.png)

### Checklist

 
 - [ ] Review spaces
 - [ ] Review arrow
 
### References

Original: https://spgatsbystg.wpengine.com/features/updates/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/updates/

**Comment by heliomar-pena** [comment]
I'm working in this issue

**Comment by heliomar-pena** [comment]
I've worked in this issue
Compare: https://wwwsimplepracticegatsbystaging-fixfeaturestemplatemainpage.gtsb.io/features/ 
With: https://spgatsbystg.wpengine.com/features/

**Comment by angelik0828** [comment]
revised, it is already corrected!
