### ISSUE TITLE
Remove Releases and Packages - Microverse-Trial-2

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#171]
### Explanation:

It is recommended to remove Releases and Packages as they have no published content.

**Current result:**
 Releases and Packages do not have published content.

**Expected result:**
 That the Releases and Packages are not there since they do not have published content.

*Screen size:*
 Full screen. 

### Screenshots:

Our: 
![image](https://user-images.githubusercontent.com/103531307/167880861-aa036ae6-87ad-4cb6-803f-aee095a2c6a1.png)

### Checklist:

This issue can be closed when the following tasks are completed:
 
 - [ ] When Releases and Packages have been removed.

 
### References:

Our: https://github.com/Israel-Laguan/Microverse-trial-2

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/168328074-8f6c4d6c-a3bc-4594-84f1-ba72001139d2.png)
in this repository this was due to some error in the upload ?

**Comment by Israel-Laguan** [comment]
Yes, was mistake, should be fixed
