### ISSUE TITLE
Missing description and details of the project.

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#172]
### Explanation
When entering the page, everything is missing, description and details of the project.

**Actual result:**
When entering the page you have no information regarding the subject referred to in the title.

**Expected result:**
That when entering the page you see information regarding the topic that the title refers to..

*Screen size:*
all screens

### Screenshots
![image](https://user-images.githubusercontent.com/74306449/167911085-f4b2e7a2-8041-4e25-a9b0-316b88809712.png)

### Check list
This issue can be closed when the following tasks are completed:
-Verify that the page is active correctly.
 
### References
https://github.com/Israel-Laguan/toy-blocks-client-react

**Comment by Israel-Laguan** [comment]
This was a repo from another organization, so I was not able to change such things.
