### ISSUE TITLE
Images and photos vs redirect

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#173]
### Explanation
When entering the page and clicking on a representative image or photo, it redirects to another page, not meaning this is a necessary fact according to the purpose of the object.

**Actual result:**
When entering the page and clicking on an image or photo, it redirects to another page without this being the objective of it.

**Expected result:**
That when entering the page and clicking on an image or photo, you do not perform any action except as indicated in an attached clip or link.

*Screen size:*
all screens

### Screenshots
some examples are attached, verify all the images and photos of each page

![image](https://user-images.githubusercontent.com/74306449/167915765-b8f7b942-183d-4626-99e5-21085a328bbc.png)
![image](https://user-images.githubusercontent.com/74306449/167915817-6789cf0b-2f8f-410f-bc47-9b7212281e3f.png)
![image](https://user-images.githubusercontent.com/74306449/167916374-299f1ad3-c1bc-42a5-8de6-3e81cad0013f.png)
![image](https://user-images.githubusercontent.com/74306449/167916448-981f2f89-2a9c-42ec-baa7-d39b4c00fb61.png)
![image](https://user-images.githubusercontent.com/74306449/167916911-91b90684-11d4-4987-9569-ad48d9edd610.png)
![image](https://user-images.githubusercontent.com/74306449/167916971-6dca50fb-4bbf-4227-b3db-012ddab1ca79.png)
![image](https://user-images.githubusercontent.com/74306449/167917008-7edd7df1-b7dc-493b-98c2-68d48787ce78.png)
![image](https://user-images.githubusercontent.com/74306449/167917211-13270a44-24e9-4a3c-b9fc-a6d63b0896e6.png)
![image](https://user-images.githubusercontent.com/74306449/167918728-85ff1f7f-3e3b-4f09-8964-d45c405a5cac.png)
![image](https://user-images.githubusercontent.com/74306449/167918962-0c71b14c-01a9-4d81-8edf-27c83c574215.png)

### Check list
This issue can be closed when the following tasks are completed:
-The images of each page are verified.
 
### References
https://github.com/Israel-Laguan/microverse-trial-3
https://github.com/Israel-Laguan/microverse-trial-4
https://github.com/Israel-Laguan/yjs-react-example
https://github.com/Israel-Laguan/textedit-app
https://github.com/Israel-Laguan/FaircoinRPS
https://github.com/Israel-Laguan/express-server-jwt
https://github.com/Israel-Laguan/guimy-backend
https://github.com/Israel-Laguan/movie-discover
https://github.com/Israel-Laguan/healthy-foodie
https://github.com/Israel-Laguan/israel-laguan.github.io
https://github.com/Israel-Laguan/Israel-Laguan
https://github.com/Israel-Laguan/Advanced-Building-Blocks---Bubble-Sort
https://github.com/Israel-Laguan/arduino-relay-app/
https://github.com/Israel-Laguan/Shopeasy
https://github.com/Israel-Laguan/React-SaaS-E-Commerce-Starter
https://github.com/Israel-Laguan/credit-card-component
https://github.com/Israel-Laguan/express-graphql-mongoose
https://github.com/Israel-Laguan/HTML-CSS-JS-Webpack-starter
https://github.com/Israel-Laguan/parrot-echo
https://github.com/Israel-Laguan/proximity-post-it

**Comment by Israel-Laguan** [comment]
This behavior can not be controlled by us, so this issue is invalid
