### ISSUE TITLE
Change Image  "Building-with-Backgrounds-And-Gradients"  /  Cambiar Imagen  "Building-with-Backgrounds-And-Gradients"

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#174]
### Explanation:
The image that exists is not consistent with the content, it is recommended to implement an image that is consistent with the content.

**Current result:** 
The image does not match the content of the page.

**Expected result:** 
That there is an image according to the content of the page.

*Screen size:*
 Full screen. 

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/167923565-09b150ef-219b-4393-9fb3-2cafeb790fe4.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] When an image according to the content has been implemented.

### References:
Our: https://github.com/Israel-Laguan/Building-with-Backgrounds-and-Gradients

Spanish Version:

### Explicación:
La imagen que existe no es consistente con el contenido, se recomienda implementar una imagen que sea consistente con el contenido.

**Resultado actual:**
La imagen no coincide con el contenido de la página.

**Resultado Esperado:**
Que haya una imagen acorde al contenido de la página.

*Tamaño de pantalla:*
 Pantalla completa.

### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/167923565-09b150ef-219b-4393-9fb3-2cafeb790fe4.png)

### Lista de Verificación:

Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Cuando se ha implementado una imagen acorde al contenido.

### Referencias:
Nuestro: https://github.com/Israel-Laguan/Building-with-Backgrounds-and-Gradients

**Comment by Israel-Laguan** [comment]
@angelik0828 what image do you recommend?

**Comment by mdrianislam0or1** [comment]
@Israel-Laguan i add a image that is related to the content and create a pull request in that project.
![change-img](https://user-images.githubusercontent.com/67714964/168198278-a18b963e-dc41-42e8-9192-c20b0af16122.jpg)

**Comment by mdrianislam0or1** [comment]
@Israel-Laguan is it that changing the image depends on the contents?

**Comment by Israel-Laguan** [comment]
Hmm maybe some image related to gradients in CSS?

**Comment by mdrianislam0or1** [comment]
changed image related with the content.


![fix](https://user-images.githubusercontent.com/67714964/168577249-94b50695-5db2-40c6-a88e-ef0dddc9aa40.jpg)

**Comment by mdrianislam0or1** [comment]
https://github.com/Israel-Laguan/Building-with-Backgrounds-and-Gradients/pull/8

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171159883-7eb173d3-2b67-4e63-9c61-4a8ca3923773.png)
