### ISSUE TITLE
Missing Content On The Page That References The Page Title  /  Falta Contenido En La Página Que Hace Referencia Al Título De La Página

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#175]
### Explanation:
When entering the page, there is no information to what the title refers to, there is only the table of contents with the corresponding information, a screen of another page is attached that if it has the information regarding the reason for the title is mentioned.

**Current result:**
When entering the page, there is no information regarding the title that the page mentions.

**Expected result:**
That when entering the page you will find relevant information, as indicated by the title of the page.

*Screen size:*
Full screen.

### Screenshots:

![image](https://user-images.githubusercontent.com/74306449/167924276-842c0b0e-a1dc-4534-b930-cf055fa0dbdf.png)
![image](https://user-images.githubusercontent.com/74306449/167924353-afe7fb64-4ba1-43bd-b2a7-e6fccb96f6a7.png)

Another page:
![image](https://user-images.githubusercontent.com/74306449/168332392-1dcaa317-ee19-4ec1-b1f3-6f4266507e29.png)
![image](https://user-images.githubusercontent.com/74306449/168332501-9b61cd69-899d-4ff0-abc3-0fcb83e7041b.png)

### Check list:

This issue can be closed when the following tasks are completed:
- Verify that the information is correct.
 
### References:
https://github.com/Israel-Laguan/microverse-trial-3
https://github.com/Israel-Laguan/microverse-trial-4

https://github.com/Israel-Laguan/textedit-app
https://github.com/Israel-Laguan/yjs-react-example

Spanish Version:

### Explicación:
Al entrar a la página no hay información a la que hace referencia el título, solo está el índice con la información correspondiente, se adjunta una pantalla de otra página que si tiene la información referente al motivo del título se menciona.

**Resultado actual:**
Al ingresar a la página, no hay información respecto al título que menciona la página.

**Resultado Esperado:**
Que al ingresar a la página encontrará información relevante, tal como lo indica el título de la página.

*Tamaño de pantalla:*
Pantalla completa.

### Capturas de pantalla:

![imagen](https://user-images.githubusercontent.com/74306449/167924276-842c0b0e-a1dc-4534-b930-cf055fa0dbdf.png)
![imagen](https://user-images.githubusercontent.com/74306449/167924353-afe7fb64-4ba1-43bd-b2a7-e6fccb96f6a7.png)

Otra página:
![imagen](https://user-images.githubusercontent.com/74306449/168332392-1dcaa317-ee19-4ec1-b1f3-6f4266507e29.png)
![imagen](https://user-images.githubusercontent.com/74306449/168332501-9b61cd69-899d-4ff0-abc3-0fcb83e7041b.png)

### Lista de Verificación:

Este problema se puede cerrar cuando se completen las siguientes tareas:
- Verificar que la información sea correcta.
 
### Referencias:
https://github.com/Israel-Laguan/microverse-trial-3
https://github.com/Israel-Laguan/microverse-trial-4

https://github.com/Israel-Laguan/textedit-app
https://github.com/Israel-Laguan/yjs-react-example

**Comment by Israel-Laguan** [comment]
It will need some proposal, maybe @anaceciliamolinares can help?

**Comment by anaceciliamolinares** [comment]
Saludos. El issue ya fue revisado aunque no tiene la validación de
Angélica. Pero si dsps de pasar por la validación se encontraran algunos
detalles para corregirlo, se hará sin ningún problema.

**Comment by anaceciliamolinares** [comment]
There are also some issues to be corrected. This only lacks validation and
reviewing from Emm and Angélica for the last grammar review.

**Comment by mdrianislam0or1** [comment]
How can I solve this issue?is there any result screen short?

**Comment by mdrianislam0or1** [comment]
Created pull request.

**Comment by Israel-Laguan** [comment]
> Created pull request.

Good work!

**Comment by mdrianislam0or1** [comment]
https://github.com/Israel-Laguan/microverse-trial-3/pull/3
https://github.com/Israel-Laguan/microverse-trial-4/pull/5
https://github.com/Israel-Laguan/textedit-app/pull/3
https://github.com/Israel-Laguan/yjs-react-example/pull/3

**Comment by angelik0828** [comment]
Everything has been checked!
