### ISSUE TITLE
Change Image - Microverse-Basic-HTML-Proyect-One  /  Cambiar Imagen - Microverse-Basic-HTML-Proyect-One

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#177]
### Explanation:

The image that exists is not consistent with the content. It is recommended to implement an image that is consistent with the content.

**Current result:** 
The image does not match the content of the page.

**Expected result:** 
That there is an image according to the content of the page.

*Screen size:* Full screen.

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/168107936-1523f3b6-33bd-4894-87a9-1d3d67618ee2.png)

### Checklist:

This issue can be closed when the following tasks are completed:
 
 - [ ] When an image according to the content has been implemented.

### References:

Our: https://github.com/Israel-Laguan/Microverse-Basic-HTML-Proyect-One

Spanish Version:

### Explicación:

La imagen que existe no es consistente con el contenido. Se recomienda implementar una imagen que sea consistente con el contenido.

**Resultado actual:**
La imagen no coincide con el contenido de la página.

**Resultado Esperado:**
Que haya una imagen acorde al contenido de la página.

*Tamaño de pantalla:* Pantalla completa.

### Capturas de pantalla:
Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/168107936-1523f3b6-33bd-4894-87a9-1d3d67618ee2.png)

### Lista de Verificación:

Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Cuando se ha implementado una imagen acorde al contenido.

### Referencias:

Nuestro: https://github.com/Israel-Laguan/Microverse-Basic-HTML-Proyect-One

**Comment by mdrianislam0or1** [comment]
is it that changing the image depends on the contents?

**Comment by mdrianislam0or1** [comment]
@Israel-Laguan i add an image related to the content and create a pull request.
![change-img](https://user-images.githubusercontent.com/67714964/168198876-259e598a-1e2c-401e-8b2d-4e792e982dee.jpg)

**Comment by mdrianislam0or1** [comment]
https://github.com/Israel-Laguan/Microverse-Basic-HTML-Proyect-One/pull/4

**Comment by angelik0828** [comment]
Everything has been checked!
