### ISSUE TITLE
Change The Color Of The Text Below The Image - Features

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#18]
### Explanation:

The color of the text under the image is not the same color as the original.

*Screen size:* (All resolutions ).

### Screenshots

Original: ![image](https://user-images.githubusercontent.com/4030477/160889057-05a39fc3-4bd9-4ce8-af2c-82408a396b53.png)
Our: 
![image](https://user-images.githubusercontent.com/4030477/160889184-2ede5b9e-6cd1-485b-8f18-caa7668eb1e4.png)
 

### Checklist

 - [ ] Change text color. 
  
### References:
 

Original: https://spgatsbystg.wpengine.com/features/
Our: https://wwwsimplepracticegatsbystaging.gtsb.io/features/

**Comment by arodriguezl9302** [comment]
I would like to be assigned to this task  @Katsu08

**Comment by heliomar-pena** [comment]
I've worked this task

**Comment by heliomar-pena** [comment]
I've worked in this issue
Compare: https://wwwsimplepracticegatsbystaging-fixfeaturestemplatemainpage.gtsb.io/features/ 
With: https://spgatsbystg.wpengine.com/features/

**Comment by angelik0828** [comment]
Resolved!!
