### ISSUE TITLE
Remove Releases And Packages / Vscode-Extension-React-Snippets  /  Eliminar Versiones Y Paquetes / Vscode-Extension-React-Snippets

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#180]
### Explanation:

It is recommended to remove Releases and Packages as they have no published content.

**Actual result:** 
Releases and Packages do not have published content.

**Expected result:** 
That the Releases and Packages are not there since they do not have published content.

*Screen size:* Full screen. 

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/168120445-961e1afd-3cd5-47bb-a546-26608dc536e0.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] When Releases and Packages have been removed.

### References:
Our: https://github.com/TheRandomCrew/vscode-extension-react-snippets

Spanish Version:

### Explicación:

Se recomienda eliminar Versiones y Paquetes ya que no tienen contenido publicado.

**Resultado actual:**
Los lanzamientos y packs no tienen contenido publicado.

**Resultado Esperado:**
Que las Versiones y Paquetes no esténn ahí ya que no tienen contenido publicado.

*Tamaño de pantalla:* Pantalla completa.

### Capturas de pantalla:

Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/168120445-961e1afd-3cd5-47bb-a546-26608dc536e0.png)

### Lista de Verificación:

Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Cuando se hayan eliminado Versiones y Paquetes.

### Referencias:

Nuestro: https://github.com/TheRandomCrew/vscode-extension-react-snippets

**Comment by e-azocar** [comment]
@Israel-Laguan is this issue only for the repository owner?

**Comment by Israel-Laguan** [comment]
> @Israel-Laguan is this issue only for the repository owner?

Yes, I do it manually
