### ISSUE TITLE
Remove Releases and Packages /  Dotfiles  /  Quitar Versiones Y Paquetes/Dotfiles

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#181]
### Explanation:

It is recommended to remove Releases and Packages as they have no published content.

**Current result:** 
Releases and Packages do not have published content.

**Expected result:**
 That the Releases and Packages are not there since they do not have published content.

*Screen size:* Full screen. 

### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/168123067-7d52fc38-55e8-4855-a72d-db710f4b811a.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] When Versions and Packages have been removed.

### References:
Our: https://github.com/Israel-Laguan/dotfiles

Spanish Version:

### Explicación:
Se recomienda eliminar Versiones y Paquetes ya que no tienen contenido publicado.

**Resultado actual:**
Los lanzamientos y paquetes no tienen contenido publicado.

**Resultado Esperado:**
 Que los Versiones y Paquetes no estén ahí, ya que no tienen contenido publicado.

*Tamaño de pantalla:* Pantalla completa.

### Capturas de pantalla:
Nuestra:
![imagen](https://user-images.githubusercontent.com/103531307/168123067-7d52fc38-55e8-4855-a72d-db710f4b811a.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completan las siguientes tareas:
 
 - [ ] Cuando se hayan eliminado Versiones y Paquetes.

### Referencias:
Nuestra: https://github.com/Israel-Laguan/dotfiles

**Comment by mdrianislam0or1** [comment]
The issue description is not clear. Can you please clear it? There are no Releases and Packages, but you said that remove those? @e-azocar please tell me about it.

**Comment by e-azocar** [comment]
@mdrianislam0or1 I think this issue is for the repository's owner
