### ISSUE TITLE
The Image Displayed On The Profile Is Incomplete  /  La Imagen Que Se Muestra En El Perfil Está Incompleta

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#182]
### Explanation:
The image shown on the profile is incomplete.

**Current result:**
 The developer profile does not have an image showing the languages it handles.

**Expected result:**
 A developer image should appear showing which languages ​​it supports.

*Screen size:* ( Fullscreen )

### Screenshots:
![image](https://user-images.githubusercontent.com/4030477/168329820-9a885f2f-c94a-469b-b8a3-99753d07915c.png)

### Checklist:

 - [ ] Place developer image.
### References:
Repository:
https://github.com/Israel-Laguan/Microverse-trial-2
https://github.com/Israel-Laguan/dotfiles
https://github.com/Israel-Laguan/irla-facebook
https://github.com/Israel-Laguan/MathMagicians-Calculator
https://github.com/Israel-Laguan/Using-Bootstrap
https://github.com/Israel-Laguan/Restaurant-Page#readme

Spanish Version:

### Explicación:

La imagen que se muestra en el perfil está incompleta.

**Resultado actual:**
 El perfil de desarrollador no tiene una imagen que muestre los idiomas que maneja.

**Resultado Esperado:**
 Debería aparecer una imagen de desarrollador que muestre qué idiomas admite.

*Tamaño de pantalla:* (Pantalla completa)

### Capturas de pantalla:
![imagen](https://user-images.githubusercontent.com/4030477/168329820-9a885f2f-c94a-469b-b8a3-99753d07915c.png)

### Lista de Verificación:

 - [ ] Coloque la imagen del desarrollador.
### Referencias:
 
Repositorio:
https://github.com/Israel-Laguan/Microverse-trial-2
https://github.com/Israel-Laguan/dotfiles
https://github.com/Israel-Laguan/irla-facebook
https://github.com/Israel-Laguan/MathMagicians-Calculator
https://github.com/Israel-Laguan/Using-Bootstrap
https://github.com/Israel-Laguan/Restaurant-Page#readme

**Comment by mdrianislam0or1** [comment]
The image represents what kind of language knows the developer.is it about adding the image everywhere?

**Comment by mdrianislam0or1** [comment]
@e-azocar  should i use <img src="https://raw.githubusercontent.com/Israel-Laguan/Israel-Laguan/master/docs/banner.jpg"/> img in every repository?

**Comment by e-azocar** [comment]
> @e-azocar should i use ![](https://raw.githubusercontent.com/Israel-Laguan/Israel-Laguan/master/docs/banner.jpg) img in every repository?

It's a question for @Israel-Laguan, but, I think that image is ok

**Comment by Israel-Laguan** [comment]
> should i use ![img](https://raw.githubusercontent.com/Israel-Laguan/Israel-Laguan/master/docs/banner.jpg) in every repository?

I think yes, please use the same image in all the repos

**Comment by mdrianislam0or1** [comment]
https://github.com/Israel-Laguan/Microverse-trial-2/pull/3
https://github.com/Azordev/dotfiles/pull/1
https://github.com/Israel-Laguan/irla-facebook/pull/4
https://github.com/Israel-Laguan/MathMagicians-Calculator/pull/20
https://github.com/Israel-Laguan/Using-Bootstrap/pull/3
https://github.com/Israel-Laguan/Restaurant-Page/pull/7

**Comment by angelik0828** [comment]
Everything has been checked!!
