### ISSUE TITLE
Change of position of the content according to resolution

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#183]
### Explanation
From 1024x633 resolution onwards all content is displayed in different positions from the original.

**Actual result:**
When entering the application for 1024x633 resolution, the images, text and buttons are in different positions compared to the original.

**Expected result:**
That when entering the application for 1024x633 resolution the images, text and buttons are the same as the original.

*Screen size:*
1024x633 and larger.

### Screenshots

Original:
![image](https://user-images.githubusercontent.com/74306449/169627007-b801dada-b596-442b-92e6-5ebc2f89d86a.png)

Our:
![image](https://user-images.githubusercontent.com/74306449/169627045-2eb2e1c7-8881-4b95-9444-ec9b6deb86ed.png)

### Check list
This issue can be closed when the following tasks are completed:
  -Verify that the images are in the correct position.
-Verify that the text is located in the correct place.
-Verify that the accept button is below.
 

 
### References
Original:
https://www.figma.com/proto/tbhMgDT10bbVjB9GazF97y/maps-proyect?node-id=434%3A1844&scaling=min-zoom&page-id=407%3A46
Our:
https://3000-azordev-mapsproject-hvy8dr6x4jd.ws-us45.gitpod.io/

**Comment by Coolhatena** [comment]
Hi, I tried to access the "our" link, but it seems to be down, its correctly written?
![Captura](https://user-images.githubusercontent.com/94434891/169682830-0264f051-11b0-4026-b5c4-470af31a1913.PNG)

**Comment by angelik0828** [comment]
@anaPiris   it's in the wrong repository
