### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#185]
### Explanation
The "go back" indicator located at the top left of the page does not have the corresponding logo as shown in the original and also when clicking does not fulfill the function of going back.

**Actual result:**
When entering the application, the indicator "go back" does not have the corresponding logo and does not fulfill the function of going back when clicking on it.

**Expected result:**
That when entering the application the "go back" indicator has the corresponding logo and fulfills the function of going back when clicking on it.

*Screen size:*
1024x633 and all other resolutions.

### Screenshots
Original:
![image](https://user-images.githubusercontent.com/74306449/169721762-768ae8fe-fbd8-4470-9730-dd1bf02825b5.png)

Our:
![image](https://user-images.githubusercontent.com/74306449/169721780-61e9744b-4a33-4d39-8d9f-5ff5d4c05733.png)

### Check list
This issue can be closed when the following tasks are completed:
  -It is verified that the logo is correct and works when clicking on it.

  
### References
Original:
https://www.figma.com/proto/tbhMgDT10bbVjB9GazF97y/maps-proyect?node-id=420%3A148&scaling=min-zoom&page-id=407%3A46
Our:
https://3000-azordev-mapsproject-ra2fw21mb7f.ws-us45.gitpod.io/check

**Comment by angelik0828** [comment]
@anaPiris it's in the wrong repository
