### ISSUE TITLE
Incorrect text

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#186]
### Explanation
The text under the title says "enter your ticket number" and in the original it says "Enter the ticket number" and the letter is in a larger size.

**Actual result:**
When entering the page, under the title it says "enter your ticket number" and it should say "Enter the ticket number" and also the font is larger.

**Expected result:**
That when entering the page, under the title it reads "Enter the ticket number" and the letter looks smaller as in the original.

*Screen size:*
1024x633 and all other resolutions.

### Screenshots
Original:
![image](https://user-images.githubusercontent.com/74306449/169722730-471940a1-4a1b-4773-ad13-452905b76e74.png)

Our:
![image](https://user-images.githubusercontent.com/74306449/169722700-3d6ecd55-7379-4f0a-aeee-d353b645e32f.png)

### Check list
This issue can be closed when the following tasks are completed:
-Verify that the text was changed and is correct.

  
### References
Original:
https://www.figma.com/proto/tbhMgDT10bbVjB9GazF97y/maps-proyect?node-id=420%3A148&scaling=min-zoom&page-id=407%3A46
Our:
https://3000-azordev-mapsproject-ra2fw21mb7f.ws-us45.gitpod.io/check

**Comment by angelik0828** [comment]
@anaPiris it's in the wrong repository
