### ISSUE TITLE
 Cropped Image Fix- Features

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/various-tasks#19]
### Explanation:

Image appears cropped at bottom at all sizes, needs to be corrected.

*Screen size:* All sizes.

### Screenshots:

**Original:**

![image](https://user-images.githubusercontent.com/101886534/160951107-1e6df5b4-f6d9-424e-9cfc-8d3d11d373cb.png)

**Our:**

![image](https://user-images.githubusercontent.com/101886534/160951250-6ce866be-39ec-466e-be31-11ab9020cc41.png)

### Checklist
 (Describe the key points to complete the task. This points will help in the pull request test.)

 This issue can be closed when the following tasks are completed:
 
 - [ ] Fix image not cropped at all sizes.

### References
 (Add the links: Original and Gatsby, where you've find the bug).

Original: http://spgatsbystg.wpengine.com/features/appointment-reminders/
Our: (link) https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/appointment-reminders/

**Comment by heliomar-pena** [comment]
Thanks for the help!

**Comment by heliomar-pena** [comment]
Solved! Please check:

Original: http://spgatsbystg.wpengine.com/features/appointment-reminders/
Our: (link) https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/appointment-reminders/

**Comment by angelik0828** [comment]
fixed!
