### ISSUE TITLE
Remove gray line - wn-changing-our-plans-and-prices 

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#24]
### Explanation:

**Actual result:**
A gray line appears under the title when there is no image.

**Expected result:**
There should be no line under the title.

*Screen size:* (all resolutions).

### Screenshots

Original: 
![image](https://user-images.githubusercontent.com/4030477/161117033-3987e078-35b4-48f5-bf81-b2a93a41c9da.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/161120024-ec94bb96-68d1-4cec-a577-c505b8bca3fa.png)

**Pages where the gray line is:** 

- wn-changing-our-plans-and-prices.
- wn-set-your-location-availability.
- wn-simplepractice-is-a-top-choice-for-massage-therapists.
- wn-changing-our-plans-and-prices.
- wn-set-your-location-availability.
- wn-simplepractice-is-a-top-choice-for-massage-therapists.

### Checklist

 - [ ] Remove gray line.
  
### References

Original: https://spgatsby.wpengine.com/whats-new/were-changing-our-plans-and-prices/
Our: https://wwwsimplepracticegatsbystaging-fixwhatsnewtemplate.gtsb.io/whats-new/were-changing-our-plans-and-prices/

**Comment by heliomar-pena** [comment]
Done! Waiting build
[Pull request](https://github.com/simplepractice/www-simplepractice-gatsby/pull/480)

**Comment by heliomar-pena** [comment]
Done! Please check

[Gatsby](https://wwwsimplepracticegatsbystaging-fixwnnoimageremovinghr.gtsb.io/whats-new/were-changing-our-plans-and-prices/)
[Original](https://spgatsby.wpengine.com/whats-new/were-changing-our-plans-and-prices/)

**Comment by angelik0828** [comment]
fixed!
