### ISSUE TITLE
Image Size - wn-Virtual-Backgrounds-For-Telehealth  

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#25]
### Explanation
**Actual result:**
the image is larger than the original

**Expected result:**
the image must measure 736X631

*Screen size:* (1440X827)

### Screenshots
(Add screenshots to help explain where's and which is the bug.)

Original: 
![image](https://user-images.githubusercontent.com/4030477/161123662-2c4054e1-b1e4-4158-9618-92ab0e5e9996.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/161123599-092b2b71-4dcd-4096-a6ff-e802d8b918f5.png)

### Checklist
  
 - [ ] Resize image
 - [ ] Review lower resolutions
 
### References

Original: https://spgatsby.wpengine.com/whats-new/virtual-backgrounds-for-telehealth/
Our: https://wwwsimplepracticegatsbystaging-fixwhatsnewtemplate.gtsb.io/whats-new/virtual-backgrounds-for-telehealth/

**Comment by heliomar-pena** [comment]
Thanks for report! I've checked and the gatsby img wrapper have the same size that the original img
 
![lastscreenshot](https://user-images.githubusercontent.com/66505715/164736568-a9ac2ae1-b412-4359-87f0-0a8d17ecc310.png)

Can you confirm if the problem still exists please? @angelik0828

**Comment by angelik0828** [comment]
If it had to do with the url it was in another branch when I reported it 

Fixed!!
