### ISSUE TITLE
Add Banner To New Version - Features

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/various-tasks#26]
### Explanation:

In the WordPress version there is a landing that leads to a link that is not seen in the new version, you have to add it so that it looks exactly the same, I attach screenshots below along with the measurements in the image.

*Screen size:* (all views).

### Screenshots

Original: 

![image](https://user-images.githubusercontent.com/101886534/161150152-d5e3e08d-f70e-483f-9110-ae01924ce2a6.png)

![image](https://user-images.githubusercontent.com/101886534/161150063-4cb42c72-e237-4bde-a01f-a0b021c7d356.png)

Our:

![image](https://user-images.githubusercontent.com/101886534/161149903-53da85e6-09a8-4398-b430-ec59c1dd8267.png)

### Checklist
 (Describe the key points to complete the task. This points will help in the pull request test.)

 This issue can be closed when the following tasks are completed:
 
 - [ ] The missing banner is added-

Original: https://spgatsbystg.wpengine.com/features/#documentation/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/#documentation/

**Comment by heliomar-pena** [comment]
Someone have already added that banner @angelik0828 please check

https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/#documentation/
https://spgatsbystg.wpengine.com/features/#documentation/

**Comment by angelik0828** [comment]
The element is already there fixed!
