### ISSUE TITLE
Fix CTA Button Link - Review Partners

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/various-tasks#27]
### Explanation:

In the new version, clicking the button doesn't take you to the page it should take, if you don't get an error, the destination url needs to be fixed.

*Screen size:* (All views )

### Screenshots:

On this screen, the **Start My Free Trial** button is not working properly as it redirects the user to an error.

![image](https://user-images.githubusercontent.com/101886534/161560621-cf9d6544-50e5-47df-9153-c86a0db3e95a.png)

Original:

![image](https://user-images.githubusercontent.com/101886534/161560696-9adc242c-94ac-49f9-859f-732a4602cc58.png)

Direct to:

![image](https://user-images.githubusercontent.com/101886534/161560811-d999a63e-daac-4190-b185-bd52a8fb4e2f.png)

Our: 

![image](https://user-images.githubusercontent.com/101886534/161560696-9adc242c-94ac-49f9-859f-732a4602cc58.png)

 Direct to:

![image](https://user-images.githubusercontent.com/101886534/161560957-c5359abc-0c8b-45cf-b1cf-ca02714c2a91.png)

 This issue can be closed when the following tasks are completed:
 
 - [ ] The button directs the user to the appropriate URL.

References:

(Add the links: Original and Gatsby, where you've find the bug)

Original: http://spgatsbystg.wpengine.com/partners/ontheair/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/ontheair/

**Comment by heliomar-pena** [comment]
@Israel-Laguan sign_up page doesn't exists, what can we do? Maybe advise to seanme about this problem?

**Comment by Israel-Laguan** [comment]
Yep, I think it can be fixed by our side
