### ISSUE TITLE
Fix Button Text - Review Partners

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/various-tasks#28]
Explanation:

It is observed that the button has a different text from the original.

*Screen size:* (All views )

### Screenshots:

Original: The button text is **Get 2 months free**

![image](https://user-images.githubusercontent.com/101886534/161575600-8fa785b6-683c-49b1-bd79-da82b7c49115.png)

OurThe button text is **Get 2 months free**

![image](https://user-images.githubusercontent.com/101886534/161575301-fdf07c96-e06d-4438-a159-1cef5dc3d961.png)

 Checklist:

 This issue can be closed when the following tasks are completed:
 
 - [ ] The button text is changed.

![image](https://user-images.githubusercontent.com/101886534/161575982-bb0c910f-e0e2-4b9f-bfd5-f1f264113765.png)

 
### References:

 (Add the links: Original and Gatsby, where you have find the bug)

Original: https://spgatsbystg.wpengine.com/partners/csha/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/csha/

**Comment by heliomar-pena** [comment]
Good work! Thanks
