### ISSUE TITLE
Review and Fix Disruptot Destination URL Error - Review Partners

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/various-tasks#29]
Explanation:

When loading the Disruptot URL an error is generated and it does not allow the user to continue, you have to validate what is happening, in the original version it loads well

*Screen size:* (All views)

Original:

![image](https://user-images.githubusercontent.com/101886534/161596485-e8359788-0772-4be7-95e2-7f9e2620eb31.png)

Our:

![image](https://user-images.githubusercontent.com/101886534/161596611-e90d519d-aa38-4b17-894f-85c2e3fc0307.png)

 This issue can be closed when the following tasks are completed:
 
 - [ ] It is fixed and the URL load is correct.
 
### References:

Original: https://spgatsbystg.wpengine.com/disruptot
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/disruptot/

**Comment by heliomar-pena** [comment]
The URL that you're using is bad, can you try please using: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/disruptot instead?

**Comment by angelik0828** [comment]
fixed!
