### ISSUE TITLE
Larger margin, between text and image - features-online-booking

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#31]
### Explanation:

There is a space between the image and the text that is larger than it should be.

Actual result: 

Larger space between image and text.

Expected result: 
The space should look smaller.

*Screen size:* (1024X529 from now on )

### Screenshots
Original: 
![image](https://user-images.githubusercontent.com/4030477/162189577-04428b80-fc80-429f-ab27-46b5e7a0f8e3.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/162189478-7965d067-dbb4-40cd-9892-e397b6a23f53.png)

### Checklist
 
 - [ ] Fix top margin of the image.  
 - [ ] Check at large resolutions after 1040.
 
### References:

Original: https://spgatsbystg.wpengine.com/features/online-booking/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/online-booking/

**Comment by heliomar-pena** [comment]
I'm working in this issue

**Comment by heliomar-pena** [comment]
Ready ! 

[Pull Request](https://github.com/simplepractice/www-simplepractice-gatsby/pull/493)

**Comment by heliomar-pena** [comment]
done! 
Please check

[Gatsby](https://wwwsimplepracticegatsbystaging-fixfeaturedetailvideomargin.gtsb.io/features/online-booking/)
[Original](https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/online-booking/)

**Comment by angelik0828** [comment]
fixed!!
