### ISSUE TITLE
Monarch view space

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#33]
### Explanation

**Actual result:**
in the form, the button to continue with the data has a very large space

**Expected result:** 

the space between the button and the form should be proportional and smaller

*Screen size:* (Add the size of your screen )

### Screenshots

Original: 
![image](https://user-images.githubusercontent.com/4030477/163045576-9ab2a3b2-9a98-4c54-a07e-f68a6ee5981d.png)

Our: 

![image](https://user-images.githubusercontent.com/4030477/163045500-105957de-1b06-4665-a700-cb538c21a07d.png)

### Checklist

 - [ ] check the space between the button and the form and correct

  
### References

Original: https://spgatsbystg.wpengine.com/monarch-therapist-signup/
Our: https://wwwsimplepracticegatsbystaging-fixsimplifysignupdetails.gtsb.io/monarch-therapist-signup/

**Comment by heliomar-pena** [comment]
This is fixed. Can you check please the links provided?

**Comment by angelik0828** [comment]
fixed!!!
