### ISSUE TITLE
Dar click en logo "simplepractice" y que actualice página principal

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#35]
### Explanation
(Clicking on the "simplepractice" logo does not refresh or reload the page).

**Actual result:** (click on the "simplepractice" logo, the letter changes to dimmer, but it does not reload or refresh the main page)

**Expected result:** (that when clicking on the "simplepractice" logo, the letter changes to a lighter one, and reloads or refreshes the main page)

*Screen size:* (1920x1080)

### Screenshots
(![image](https://user-images.githubusercontent.com/74306449/163223006-3f45d4ad-0444-42ba-821a-ca5cb5945e0a.png))

Original: (image)
Our: (image)

### Checklist
 ((while on the home page, click on "simplepractice", verify that the text is smoother and reload the page).)

 This issue can be closed when the following tasks are complete:
 
 - [ ] Example 1
 - [ ] Example 2
 
### References
 (Add the links: Original and Gatsby, where you've find the bug)

Original: https://spgatsbystg.wpengine.com/
Our: [(link)](https://wwwsimplepracticegatsbystaging-fixwhatsnewtemplate.gtsb.io/)

**Comment by heliomar-pena** [comment]
I've checked and it's working correctly. Maybe it's a internet problem...

![lastscreenshot](https://user-images.githubusercontent.com/66505715/163846912-58bb6a06-92b3-4f3c-ae74-ccf278ed805e.png)

@angelik0828 can you check please if when you clicks in simplepractice logo they do what we expect?
