### ISSUE TITLE
Faltan lineas separadoras en Template Library(Progress Notes)

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#39]
### Explanation
(when entering SimplePractice/feature/Documentation) and clicking on "Template Library", the lines in the large box and in the smaller one attached are not the same as in the original.

**Actual result:**
 (when you open the box: Progress Notes: the line below "Acupuncture SOAP note" and the line under "Articulation Goal Tracker" are missing, also missing the first line in the smaller overlapping box)

**Expected result:**
 (That when opening the box there is a line below each title as shown in the original,for the large frame and the smaller frame superimposed)

* Screen Size:* (1920x1080)

### Screenshots
(![Captura web_19-4-2022_232545_wwwsimplepracticegatsbystaging gatsbyjs io](https://user-images.githubusercontent.com/74306449/164135343-ccbedc66-08cb-44ce-afb5-20b6117fb5e5.jpeg))

Original:
 (![image](https://user-images.githubusercontent.com/74306449/164136202-204f708e-fb73-4736-8ec8-185fb7d5bf95.png))

Our: 
(![image](https://user-images.githubusercontent.com/74306449/164136438-82ec068f-7dc0-4075-bab0-f58d4bc7b24a.png))

### Checklist
 (Describe the key points to complete the task. This points will help in the pull request test.)

 This issue can be closed when the following tasks are complete:
 
 - [ ] Example 1
 - [ ] Example 2
 
### References
 (Add the links: Original and Gatsby, where you've find the bug)

Original: https://spgatsbystg.wpengine.com/features/
Our: [(link)](https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/)

**Comment by Israel-Laguan** [comment]
@anaPiris Please include a checklist

@Katsu08 please confirm, as I entered and the lines are there (they indeed are faint, but are present), maybe it's just a problem with the @anaPiris 's display monitor

In any case at the end of the day, this issue maybe is the client's fault as the image is taken from them, so no action from our side.
