### ISSUE TITLE
spaces between title and text  - creative-therapy-umbrella

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#40]
### Explanation
(the space between title and text is not as expected.)

**Actual result:** (there is more space between the title and the text.)

**Expected result:** (that there is adequate space between title and text.)

*Screen size:* (1366 x 768)

### Screenshots
imagen 1
Original: (
![image](https://user-images.githubusercontent.com/103531307/164265424-ae015cf5-d41e-425f-8461-811b9f3f19ee.png)
)
Our: (
![image](https://user-images.githubusercontent.com/103531307/164265375-caf82877-86b5-423f-bbb3-a602a2e36a8d.png)
)
imagen 2
Original: (
![image](https://user-images.githubusercontent.com/103531307/164265709-e259e6de-76d6-447f-9945-06025cc1bd85.png)
)
Our: (
![image](https://user-images.githubusercontent.com/103531307/164265749-df3c7498-0fa9-4ce9-a31f-40fca97221cc.png)
)

imagen 3
Original: (
![image](https://user-images.githubusercontent.com/103531307/164265941-7bb046b8-ad6b-47e5-8721-3d3e1aac9a94.png)
)
Our: (
![image](https://user-images.githubusercontent.com/103531307/164265980-26454e81-32e3-4866-b017-bb50b5b8e823.png)
)

imagen 4
Original: (
![image](https://user-images.githubusercontent.com/103531307/164266027-a5ccb5f7-9cd4-49ab-981f-445de162af6c.png)
)
Our: (
![image](https://user-images.githubusercontent.com/103531307/164266080-173074c7-2124-4bee-9332-0b11cda043cc.png)
)

### Checklist
 
 - [ ] This activity will be closed when the distance between titles and texts is as expected.

 
### References
Original: http://spgatsbystg.wpengine.com/partners/creative-therapy-umbrella/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/creative-therapy-umbrella/

**Comment by angelik0828** [comment]
This task was already done when it was reported
![image](https://user-images.githubusercontent.com/4030477/164484557-cb04ca48-aef4-4352-b1b2-2c0080d87ba3.png)
