### ISSUE TITLE
 The Web Container s Not Taking Up 100% - Mentally Fit

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#42]
### Explanation:

The web container is not taking up 100% in the smallest resolutions.

**Current result:**

 When entering the resolution of 320 the entire application is cut off.

**Expected result:**

 The website must occupy 100% of the current page

*Screen size:*        (320X522, 375X522 )

### Screenshots:

Original: 
![image](https://user-images.githubusercontent.com/4030477/164293782-c7868a2c-a22f-4727-9002-8bbf6a02c041.png)
![image](https://user-images.githubusercontent.com/4030477/164293818-3592c98d-20bb-48e4-a5a7-7a0c0587c41a.png)
![image](https://user-images.githubusercontent.com/4030477/164295009-83d2d33d-440e-4a4e-a040-bd4942397ec6.png)
![image](https://user-images.githubusercontent.com/4030477/164295042-203d9229-dcc4-4e7f-9641-67b2012a4aa8.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/164293695-7665cb22-95c2-41f3-a2a1-00ff88af0ba6.png)
![image](https://user-images.githubusercontent.com/4030477/164293733-731d10d1-6225-414b-8e45-5031872d881d.png)
![image](https://user-images.githubusercontent.com/4030477/164294635-8e6cd266-2ca1-474c-a14f-d96596ae3e03.png)
![image](https://user-images.githubusercontent.com/4030477/164294669-faa2471c-c8b3-47b8-8549-34d96c17784e.png)

### Checklist:

 - [ ] Resolve that the web container occupies 100%.
 - [ ] Review lower resolutions.
 - [ ] Review the different pages.
 
### References:
Below are the pages where the same error occurs.

Original: https://spgatsbystg.wpengine.com/partners/mentally-fit/
https://spgatsbystg.wpengine.com/partners/ontheair/

Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/mentally-fit/
https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/ontheair/

**Comment by heliomar-pena** [comment]
I haven't found the bug that you've mentioned, maybe it's a bug that occurs just on one browser?

But I've noticed that capterra logo is missing, then I've added it and I've fixed the spaces on the reviewers section (stars, capterra logo, HiSecurity logo) 

I've fixed this that I mentioned on the branch fix/partnerIndividualBanner-capterra-logo

[PR here](https://github.com/simplepractice/www-simplepractice-gatsby/pull/556)

Waiting build

![LastRecord](https://user-images.githubusercontent.com/66505715/168846783-0d4acf68-d70e-42b8-be8b-dc4fee80edcb.gif)
