### ISSUE TITLE
Space between title and header  - On the Air

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#43]
### Explanation
when entering you see a gap between the title and the header

**Actual result:** when entering you see a gap between the title and the header

**Expected result:** when entering it must be the correct size

*Screen size:* (All resolutions )

### Screenshots

Original: 
![image](https://user-images.githubusercontent.com/4030477/164295539-1489e3c4-562b-4a2d-adcc-dc11cefad1bb.png)
![image](https://user-images.githubusercontent.com/4030477/164295763-4fa41ea5-505c-4fb4-a18c-1e6671f6a0ec.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/164295492-52e91fa3-0396-4652-a5be-015554b0e7e3.png)
![image](https://user-images.githubusercontent.com/4030477/164295714-13b5eef9-ad34-4b82-b3cf-4e9844004a5d.png)
![image](https://user-images.githubusercontent.com/4030477/164295838-b418d853-80dc-4015-9874-e54bb13afb9d.png)
![image](https://user-images.githubusercontent.com/4030477/164295866-23b055f3-6e73-4d04-a586-bb0c352ad374.png)
![image](https://user-images.githubusercontent.com/4030477/164296014-c7d0ad60-21fd-4097-9378-9b2c0b91d998.png)

### Checklist

 
 - [ ] Review spaces in title and margins
 - [ ] Review all resolutions
 
### References
 
Original: https://spgatsbystg.wpengine.com/partners/ontheair/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/ontheair/

**Comment by heliomar-pena** [comment]
Hello! Thanks for report. I think I don't get the issue or I don't see the difference between :( 
![lastscreenshot](https://user-images.githubusercontent.com/66505715/164733552-01885279-f768-4c04-8b1d-6bf949ebfab7.png)

Can you please check if the screenshots / description are correct or if this issue was be fixed?

**Comment by angelik0828** [comment]
It is not the text as such, it is the container that is bigger, please check

Original
![image](https://user-images.githubusercontent.com/4030477/165112674-7fbb9277-fbcd-4bd5-bc9b-17ff43f681e4.png)
our
![image](https://user-images.githubusercontent.com/4030477/165112908-36f0dc47-edf3-454c-878f-80cadef47390.png)

**Comment by heliomar-pena** [comment]
@angelik0828 can you explain to me again about this task?

or check if is already solved? I don't see the problem again, i'm sorry!
