### ISSUE TITLE
margin size is not as expected - speechiesideup

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#46]
### Explanation
Our margin does not match the original.

**Actual result:** the margin is 0px 0px 14px

**Expected result:** expected margin is 0px 0px 8px

*Screen size:* 1366 x 768

### Screenshots

Original: (
![image](https://user-images.githubusercontent.com/103531307/164512169-6258ac5e-bde0-494a-a3ee-bee0cd25f569.png)
)
Our: (
![image](https://user-images.githubusercontent.com/103531307/164512214-d52c0a99-4f66-48dc-b0d9-18bc47295460.png)
)

### Checklist
This issue can be closed when the following tasks are complete:
 
 - [ ] our margin matches the original.

 
### References

Original: https://spgatsbystg.wpengine.com/partners/speechiesideup/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/speechiesideup/

**Comment by heliomar-pena** [comment]
The image element size is the same that the original and it's positioned correctly

![lastscreenshot](https://user-images.githubusercontent.com/66505715/164730000-635cc1a2-0463-4179-85c1-13744635f09a.png)

In this cases where doesn't exist difference visual between the pages is not important if someone have different margin / padding, always that we get the same result
