### ISSUE TITLE
bug in the image - AATA

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#51]
### Explanation
the size on the image and the margin are not as expected.

**Actual result:** img 207 x 96 - margin 0px 0px 14px.

**Expected result:** img 206.5 x 96 - margin 0px 0px 8px.

*Screen size:* 1366 x 768 

### Screenshots
Original: (
![image](https://user-images.githubusercontent.com/103531307/164723809-b7b6c6c8-efac-47c2-88ca-9a1e9fc0f7c8.png)
)
Our: (
![image](https://user-images.githubusercontent.com/103531307/164723887-df43f334-f4aa-4cb9-bf67-abd3d1a2369b.png)
)

### Checklist
This issue can be closed when the following tasks are complete:
 
 - [ ] the size and margin of the image are as expected.
 
### References
 
Original: http://spgatsbystg.wpengine.com/partners/aata/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/aata/

**Comment by heliomar-pena** [comment]
Thanks for report! I've added wontfix since is a <1px issue
