### ISSUE TITLE
size in the image is not correct - VAND

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#52]
### Explanation
the size on the image and the margin are not as expected.

**Actual result:**  img 165 x 96 

**Expected result:** img 165.2 x 96 

*Screen size:* 1366 x 768

### Screenshots

Original: (
![image](https://user-images.githubusercontent.com/103531307/164730979-ca14c101-af99-44d8-9927-de944be0a9f8.png)
)
Our: (
![image](https://user-images.githubusercontent.com/103531307/164731017-98a4c03a-be1c-402a-900d-a69949386a04.png)
)

### Checklist
 This issue can be closed when the following tasks are complete:
 
 - [ ] the size and margin of the image are as expected.
 
 
### References

Original: http://spgatsbystg.wpengine.com/partners/vand/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/vand/

**Comment by heliomar-pena** [comment]
I've added wontfix label since is a difference of less a 1px
