### ISSUE TITLE
The list of information is not displayed completely - Simplify-practice-sign-up

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#53]
### Explanation
when entering this form when displaying the options to choose from are incomplete

**Actual result:** when entering this form when displaying the options to choose from are incomplete

**Expected result:** options should be displayed complete

*Screen size:* (all screen)

### Screenshots

Original: 
![image](https://user-images.githubusercontent.com/4030477/164784457-72ddfc2c-a205-4976-bee4-aa3a92d858d8.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/164784530-4a0ae00b-0ff6-46b4-8704-20f697162ce4.png)

### Checklist
 
 - [ ] Check that the list is complete and displayed
 
 
### References
 
Original: https://spgatsbystg.wpengine.com/simplify-practice-sign-up/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/simplify-practice-sign-up/

**Comment by heliomar-pena** [comment]
Done! Please check here: 

[Gatsby](https://wwwsimplepracticegatsbystaging-fixfixingsimplifydetails.gtsb.io/simplify-practice-sign-up/)
[Original](http://spgatsby.wpengine.com/simplify-practice-sign-up/)

**Comment by angelik0828** [comment]
fixed!! 
![image](https://user-images.githubusercontent.com/4030477/167655539-2ccd1228-7869-4e86-a803-5ac8fa9f9efe.png)
