### ISSUE TITLE
The background color does not match - simplify-practice-sign-up

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#54]
### Explanation
the background color does not match

**Actual result:** the background color is light blue

**Expected result:** the background color should be white

*Screen size:* (All screen  )

### Screenshots

Original: 
![image](https://user-images.githubusercontent.com/4030477/164787507-ecd05931-9713-45ad-806f-62f037602ff2.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/164787876-872aafdc-a97a-4e5c-aa25-6164fc2e191e.png)

### Checklist

 
 - [ ] Check and change background color
 
### References

Original: https://spgatsbystg.wpengine.com/simplify-practice-sign-up/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/simplify-practice-sign-up/

**Comment by heliomar-pena** [comment]
Done! Please check here: 

[Gatsby](https://wwwsimplepracticegatsbystaging-fixfixingsimplifydetails.gtsb.io/simplify-practice-sign-up/)
[Original](http://spgatsby.wpengine.com/simplify-practice-sign-up/)

**Comment by angelik0828** [comment]
fixed!!
