### ISSUE TITLE
The form does not have the title - Simplify-practice-sign-up

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#55]
### Explanation
when entering the form it has no title

**Actual result:** when entering the form it has no title

**Expected result:** the form is titled "Begin your free, 30-day trial."

*Screen size:* (All screen)

### Screenshots

Original: 
![image](https://user-images.githubusercontent.com/4030477/164788132-fcf423cb-18cd-4feb-84f9-c09a34ebedbb.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/164788089-901e63fc-4388-4dce-ba16-35fe32592d22.png)

### Checklist

 
 - [ ] check the title and place in the form
 
### References

Original: https://spgatsbystg.wpengine.com/simplify-practice-sign-up/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/simplify-practice-sign-up/

**Comment by heliomar-pena** [comment]
Done! Please check here: 

[Gatsby](https://wwwsimplepracticegatsbystaging-fixfixingsimplifydetails.gtsb.io/simplify-practice-sign-up/)
[Original](http://spgatsby.wpengine.com/simplify-practice-sign-up/)

**Comment by angelik0828** [comment]
fixed!!
