### ISSUE TITLE
Incorrect button information and missing text below the button - Simplify-practice-sign-up

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#56]
### Explanation
the button text and the text below do not have this format

**Actual result:** the button text and the text below do not have this format

**Expected result:** the button text should be something else and there should be some text below the button

*Screen size:* (all screen )
### Screenshots

Original: 
![image](https://user-images.githubusercontent.com/4030477/164788937-d00494f3-6e64-4d17-b1ac-9cbc922094bf.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/164788972-47589bb5-59e8-4d0c-8d0c-af8edda9e634.png)

### Checklist

 - [ ] Check button text
 - [ ] Put text below the button
 
### References
 

Original: https://spgatsbystg.wpengine.com/simplify-practice-sign-up/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/simplify-practice-sign-up/

**Comment by heliomar-pena** [comment]
Done! Please check here: 

[Gatsby](https://wwwsimplepracticegatsbystaging-fixfixingsimplifydetails.gtsb.io/simplify-practice-sign-up/)
[Original](http://spgatsby.wpengine.com/simplify-practice-sign-up/)

**Comment by angelik0828** [comment]
fixed!!!
