### ISSUE TITLE
Check list title in content

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#57]
### Explanation
when entering the page the title of the list is not seen

**Actual result:** when entering the page the title of the list is not seen

**Expected result:** The title must be in the content before the list : "Try everything from:"

*Screen size:* (all screen )

### Screenshots

Original: 
![image](https://user-images.githubusercontent.com/4030477/164789811-b2a4d835-b43e-4970-9a48-f6196b6d3ce0.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/164789699-3f5d44ce-8ec7-4eb8-b29c-5d9ccfc580e6.png)

### Checklist

 
 - [x] Check the title and that it appears before the list
 
### References

Original: https://spgatsbystg.wpengine.com/simplify-practice-sign-up/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/simplify-practice-sign-up/

**Comment by heliomar-pena** [comment]
Done! Please check here: 

[Gatsby](https://wwwsimplepracticegatsbystaging-fixfixingsimplifydetails.gtsb.io/simplify-practice-sign-up/)
[Original](http://spgatsby.wpengine.com/simplify-practice-sign-up/)

**Comment by angelik0828** [comment]
fixed!
