### ISSUE TITLE
The capcha remains on the entire page below the form fields - Sign-up-v2

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#58]
### Explanation
(A clear and concise explication about the task.)

**Actual result:** The capcha appears static on the page even at smaller resolutions

**Expected result:** verify that the capcha is in a place in the form not in the whole page

*Screen size:* (425X522, 375X522, 320X522)

### Screenshots

Original: 
![image](https://user-images.githubusercontent.com/4030477/164792911-ca6df1b4-467c-4637-bca4-eee1a06e11df.png)

Our: 
![image](https://user-images.githubusercontent.com/4030477/164792855-bb5e8d96-3c0d-4926-8273-ffd64a7726af.png)
![image](https://user-images.githubusercontent.com/4030477/164793496-b99660a0-536c-48ac-ac19-eac85d3d43ba.png)

### Checklist
 

 - [ ] Verify that the capcha is in a place in the form not in the whole page
 - [ ] Check resolutions

 
### References

Original: https://spgatsbystg.wpengine.com/simplify-practice-sign-up/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/simplify-practice-sign-up//

**Comment by heliomar-pena** [comment]
Done! Please check here:

[Gatsby](https://wwwsimplepracticegatsbystaging-fixsignupformdetails.gtsb.io/simplify-practice-sign-up/)
[Original](https://spgatsbystg.wpengine.com/simplify-practice-sign-up/)
