### ISSUE TITLE
Cropped image in “Virtual classes and webinars”

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#62]
### Explanation

In "Virtual classes and webinars" the size of the image is not the same as the original, so it is cut off at the bottom.

  **Actual result: **

When you get to "Virtual classes and webinars" you can see that the image is cut off at the bottom.

**Expected result: **

That when you get to "Virtual classes and webinars" the image looks complete as shown in the original.

  *Screen size: *

   1440x633

### Screenshots

  Original:

https://user-images.githubusercontent.com/74306449/164953526-ba501fa9-346f-40bc-9abc-5ac240015400.png

Our:

https://user-images.githubusercontent.com/74306449/164953547-079dd406-877b-4e8c-a0c3-b07a8deb77c7.png

### Check list

Verify that the image is complete in all resolutions.

  
### References

  Source: http://spgatsbystg.wpengine.com/features/support/

  Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/support/

**Comment by angelik0828** [comment]
this issue has already been created
