### ISSUE TITLE
Image size in “Comprehensive support”

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#63]
### Explanation

In “Comprehensive support” the size of the image is not equal to the original, so it is cut off at the bottom.

  **Actual result: **

When you get to “Comprehensive support” you can see that the image is cut off at the bottom.

**Expected result: **

That when reaching “Comprehensive support” the image is seen as complete as the original shows.

  *Screen size: *

   1440x633

### Screenshots

  Original:
![image](https://user-images.githubusercontent.com/74306449/165598533-70be992a-3cbc-4529-b0fd-e56097195a9c.png)

Our:
![image](https://user-images.githubusercontent.com/74306449/165598635-280e2121-2b0b-4fa0-88ae-6e11833a46dd.png)

### Check list

Verify that the image is complete in all resolutions.

  
### References

  Source: http://spgatsbystg.wpengine.com/features/support/

  Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/support/

**Comment by heliomar-pena** [comment]
Check the "1)" screen size please, it doesn't is a large screen, maybe 800-900px of width screen. Can you try to reproduce the same error using the Inspect Elements Tool to see the screen size where the error occurs

**Comment by anaPiris** [comment]
Revised, the error occurs for all resolutions, the image is cut off at the bottom.
Original
![image](https://user-images.githubusercontent.com/74306449/165759272-a8fc0731-270a-45ce-87d1-ad71056dfc4d.png)
Our
![image](https://user-images.githubusercontent.com/74306449/165759081-ab9136d8-7cb5-4bbb-96d9-a9a36a98ae66.png)
