### ISSUE TITLE
text size error - wn-taxt-report

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#67]
### Explanation
the text size does not match what is expected.

**Actual result:** the size is not as expected.

**Expected result:** that the size matches the original.

*Screen size:* all screen 

### Screenshots

Original: 
![image](https://user-images.githubusercontent.com/103531307/164995406-f9d6d063-ce43-46cb-a29a-afd09d284a0f.png)

Our: 
![image](https://user-images.githubusercontent.com/103531307/164995417-f417af15-ad24-4d57-9fe1-b477d1fb6213.png)

Original:
![image](https://user-images.githubusercontent.com/103531307/165381127-4e665165-4b92-4513-82d7-eac0a7058a89.png)

Our:
![image](https://user-images.githubusercontent.com/103531307/165381159-fff3f621-188f-4827-9ca0-fd55e8109f3c.png)

### Checklist
 This issue can be closed when the following tasks are complete:
 
 - [ ] the size of the texts is as expected.

### References

Original: http://spgatsbystg.wpengine.com/whats-new/your-2021-tax-report-is-now-available/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/whats-new/your-2021-tax-report-is-now-available/

Original: http://spgatsbystg.wpengine.com/welcome-back/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/welcome-back/

**Comment by roberto-97c** [comment]
This error occurs on all pages of this session.

**Comment by heliomar-pena** [comment]
Hello roberto! thanks for check!.
 
This doesn't affect how looks the page
Original: 
![image](https://user-images.githubusercontent.com/103531307/164995406-f9d6d063-ce43-46cb-a29a-afd09d284a0f.png)

Our: 
![image](https://user-images.githubusercontent.com/103531307/164995417-f417af15-ad24-4d57-9fe1-b477d1fb6213.png)


This doesn't affect how looks the page, that margin is the way that we've use to do our page match with the legacy page
Original:
![image](https://user-images.githubusercontent.com/103531307/165381127-4e665165-4b92-4513-82d7-eac0a7058a89.png)

Our:
![image](https://user-images.githubusercontent.com/103531307/165381159-fff3f621-188f-4827-9ca0-fd55e8109f3c.png)
