### ISSUE TITLE
type of lyrisc not is corret - wn-a-new-way-to-remind-clients-to-complete-paperwork

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#69]
### Explanation
in the text enter your email address the font is not correct

**Actual result:** the font is not as expected.

**Expected result:** the font is correct.

*Screen size:* all screen

### Screenshots

Original: (
![image](https://user-images.githubusercontent.com/103531307/165000563-589efde8-d96a-42c7-81f9-02796d02ef06.png)
)
Our: (
![image](https://user-images.githubusercontent.com/103531307/165000571-e4ce0d26-b1a8-43db-99c8-f7eee2eaf673.png)
)

### Checklist
 This issue can be closed when the following tasks are complete:
 
 - [ ] the font is as expected.

 
### References

Original: http://spgatsbystg.wpengine.com/whats-new/a-new-way-to-remind-clients-to-complete-paperwork/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/whats-new/a-new-way-to-remind-clients-to-complete-paperwork/

**Comment by roberto-97c** [comment]
This error occurs on all pages of this session.

**Comment by heliomar-pena** [comment]
Fixed, please check in this link:

[Gatsby](https://wwwsimplepracticegatsbystaging-fixvariousfixes.gtsb.io/whats-new/a-new-way-to-remind-clients-to-complete-paperwork/)
[Original](http://spgatsbystg.wpengine.com/whats-new/a-new-way-to-remind-clients-to-complete-paperwork/)

**Comment by angelik0828** [comment]
the size is not correct the size varies by 2 px on different screens, It should be considered?
![image](https://user-images.githubusercontent.com/4030477/167659650-3c88e39b-0d08-4e44-8221-99e5ed05a4a3.png)
![image](https://user-images.githubusercontent.com/4030477/167659688-5a2ab7f7-851d-4183-89f9-84f41cf1868e.png)
![image](https://user-images.githubusercontent.com/4030477/167660381-d84db7c1-314f-4f61-9c9e-f6af2a923e62.png)

**Comment by heliomar-pena** [comment]
Thanks @angelik0828 I'll check that error
