### ISSUE TITLE
Box size error in "Keep information safe"

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#72]
### Explanation

In "Keep information safe” the box with the image is cut off in the upper left part of it.

   **Actual result: **

When entering "Keep information safe” the box with the image on the left is cut off at the top of it.

**Expected result: **

That when entering "Keep information safe" the box with the image on the left is seen completely.

* *Screen size: *

  Large screen

## Screenshots

Original:
![image](https://user-images.githubusercontent.com/74306449/165597604-ac1b1332-337a-4442-a9d6-9c041b2a6bfb.png)
Our:
![image](https://user-images.githubusercontent.com/74306449/165597719-02ebc923-70c4-456b-a41e-9e2e304c2636.png)

### Check list

 - [ ]  Verify that the box looks complete for all screen resolutions.
 - [ ] Error presented in other views attached link

  
### References

  Source: http://spgatsbystg.wpengine.com/features/credit-card-processing/
  https://spgatsbystg.wpengine.com/features/group-practice/

  Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/credit-card-processing/
  https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/group-practice/

**Comment by heliomar-pena** [comment]
Perfect, good work!

**Comment by heliomar-pena** [comment]
This was done by simple practice's developers
