### ISSUE TITLE
text color is not correct- "pricing" 

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#75]
### Explanation
the color of the text does not match the original.

**Actual result:** the color of the text is not as expected.

**Expected result:** the color of the text matches the original.

*Screen size:* all screen

### Screenshots

Original: (
![image](https://user-images.githubusercontent.com/103531307/165124363-bbb2449c-ad0f-44fe-9f7e-f68d9f8f7603.png)
)
Our: (
![image](https://user-images.githubusercontent.com/103531307/165124407-bf97efc9-1293-4e8d-b41c-7b244eec0037.png)
)

### Checklist
This issue can be closed when the following tasks are complete:
 
 - [ ] the color of the text is as expected.

### References

Original: https://spgatsbystg.wpengine.com/pricing/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/pricing/

**Comment by roberto-97c** [comment]
this error is in general in the session - WN Template.

**Comment by heliomar-pena** [comment]
Fixed please check @angelik0828 

Original: https://spgatsbystg.wpengine.com/pricing/
Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/pricing/

**Comment by angelik0828** [comment]
fixed!!
