### ISSUE TITLE
In "Your all-in-one private practice partner” difference in spaces and image size.

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#77]
### Explanation

In "Your all-in-one private practice partner” difference in spaces.

 **Actual result: **

When entering "Your all-in-one private practice partner” the box where the mail is entered and the line of stars is seen with a slight movement due to the different spaces between them.

**Expected result: **

That when entering "Your all-in-one private practice partner” the image is seen in the same way as in the original.

* *Screen size: *

1440x633

### Screenshots
the letter of “enter your email” is observed smaller
Original: 
![image](https://user-images.githubusercontent.com/74306449/165596198-b19a090b-614a-4508-a466-eea62dc264d1.png)
Our:
![image](https://user-images.githubusercontent.com/74306449/165596379-25531de0-08ea-40d4-bfda-22ab6c07ea95.png)

### Screenshots
​difference in image size for this resolution
Original: 
![image](https://user-images.githubusercontent.com/74306449/165596607-8144adde-7200-48d5-a996-a437989c2736.png)
Our:
![image](https://user-images.githubusercontent.com/74306449/165596820-fcdfe6ff-68ab-4bbe-ab97-744a2152ff60.png)

### Check list

1-Verify that the indicated spaces are the same for all resolutions.

2-Verify that the size of the image is equal to the original for the 768x633 resolution.

  
### References

 Original:http://spgatsbystg.wpengine.com/features/#documentation

 Our:https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/#documentation

**Comment by heliomar-pena** [comment]
I will check this issue

**Comment by heliomar-pena** [comment]
Working on branch fix/FeatureHeroVideo-fix-size

**Comment by heliomar-pena** [comment]
[PR Here](https://github.com/simplepractice/www-simplepractice-gatsby/pull/555)

Waiting for build
