### ISSUE TITLE
In "Your practice in your pocket” difference in font size in email entry

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#78]
### Explanation

In "Your practice in your pocket” there is a difference in the font size in the “enter your email” field

   **Actual result: **

When entering "Your practice in your pocket" it is observed that the font size changes to smaller.

**Expected result: **

That when entering "Your practice in your pocket" the letter is seen in the same way as in the original.

* *Screen size: *

1024x633

### Screenshots

Original:
https://user-images.githubusercontent.com/74306449/165306213-90ccdf58-180c-4ad6-ac53-c3a214e9b675.png
Our:
https://user-images.githubusercontent.com/74306449/165306364-876ae219-d29e-4ce5-b9d7-7c88241ecd74.png

### Check list

Verify that the indicated spaces are the same for all resolutions.

  
### References

Original:http://spgatsbystg.wpengine.com/features/mobile-app/

  Our:https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/mobile-app/

**Comment by angelik0828** [comment]
this issue has already been created
