### ISSUE TITLE
Cropped image at:"Built for iPhone and Android”

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#79]
### Explanation

In "Built for iPhone and Android” the image is cut off.

  **Actual result: **

Entering "Built for iPhone and Android" shows that the image is cut off at the top.

**Expected result: **

That when entering "Built for iPhone and Android" the image is seen complete as in the original.

* *Screen size: *

1024x633

### Screenshots

Original:
1)https://user-images.githubusercontent.com/74306449/165311764-2095ae20-f44d-4b0a-9900-a9a96da5dcf2.png
2)https://user-images.githubusercontent.com/74306449/165312987-afe045d6-9308-4103-a2f4-38ac39c26379.png
3)https://user-images.githubusercontent.com/74306449/165313567-be2fa955-b519-40df-8088-6e6c1cdbd27a.png
4)https://user-images.githubusercontent.com/74306449/165313882-a70b042f-952f-40b9-9307-2627d78bb1aa.png

Our:
1)https://user-images.githubusercontent.com/74306449/165311830-5009ccf3-7387-4c65-969d-302775882de9.png
2)https://user-images.githubusercontent.com/74306449/165313197-f7e15313-9bd5-497b-b098-934592d8a2df.png
3)https://user-images.githubusercontent.com/74306449/165313677-0ad370a2-db89-466e-b088-0ca6d1d186c3.png
4)https://user-images.githubusercontent.com/74306449/165313982-ee1a4172-827d-4ec8-91a4-4f5e57b4d2b5.png

### Check list

Verify that the image looks the same for all resolutions.

  
### References

Original:http://spgatsbystg.wpengine.com/features/mobile-app/

  Our:https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/mobile-app/

**Comment by angelik0828** [comment]
this issue has already been created
