### ISSUE TITLE
Membership Cards Have A Lot Of Separation Between The Title And The Subtitle.

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/various-tasks#8]
### Explanation:

In [Partner View](https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/), in the section: "Help your network to be the best version of themselves (business)" there are some cards that have a title and a description. . I have noticed that the space between the title and the description is too large and needs to be corrected. I have also noticed that the image does not take up 100% of the width, there is a right border which makes the image smaller.

### Screenshot
![image](https://user-images.githubusercontent.com/66505715/160475083-76ac8fb1-a510-4306-8139-5208abd5885f.png)
![image](https://user-images.githubusercontent.com/66505715/160475107-658c54a9-8516-4562-8fc3-b9b2a26eaccf.png)

### Checklist
- [ ] The space between title and subtitle is the same.
- [ ] The image is occupying 100% of the width.

### References
Gatsby: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/
Original: http://spgatsbystg.wpengine.com/partners/

**Comment by heliomar-pena** [comment]
Done

please compare https://wwwsimplepracticegatsbystaging.gtsb.io/partners/
with https://spgatsbystg.wpengine.com/partners/

@angelik0828

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/165110737-06325dd5-50b9-47aa-a857-476c37b713bd.png)

I don't see the change @Katsu08

**Comment by heliomar-pena** [comment]
Our: Left
Original: Right
![lastscreenshot](https://user-images.githubusercontent.com/66505715/165595571-ba3758fc-8da8-46c1-90d2-6547f5338662.png)

The issue is about the space between the title (Ebooks) and the description (A Clinician....)

Can you check again please?

**Comment by angelik0828** [comment]
I see it much better, it's fixed!!
