### ISSUE TITLE
Component Unit Test #3

### ISSUE THREAD

**Issue by angelik0828** [Azordev/various-tasks#85]
## Explanation

In SP we need to create unit tests for some components, in this task you will see collected 5 components that do not have unit tests and need to be added, each component must meet the following tests:

- Snapshot
- Is render correctly
- Functionality tests if apply
- Negative tests if apply

The components that are being mentioned are inside **/src/components**, first you should go to **src/components,** and then follow the path that the checklist says: for example **src/components/Modals/EmailCaptureSubmitBtn**

### Checklist

- [ ] Modals/BtnCloseEmailModalWrapper has the tests mentioned in the explanation
- [ ] Modals/EmailCaptureModal has the tests mentioned in the explanation
- [ ] Modals/Modal has the tests mentioned in the explanation
- [ ] Modals/EmailCaptureContent has the tests mentioned in the explanation
- [ ] Modals/EmailCaptureSubmitBtn has the tests mentioned in the explanation

**Comment by Saikilito** [comment]
Test sent in the `feat/Modals-test` branch

**Comment by heliomar-pena** [comment]
[Pull Request](https://github.com/simplepractice/www-simplepractice-gatsby/pull/478)

**Comment by heliomar-pena** [comment]
Good work!
