### ISSUE TITLE
Partners articles have so much space between description and image (914x709)

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/various-tasks#9]
### Explanation
In [Partners view ](https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/), at the section: "Helping Practitioners in your Network" they're some articles that have title, description and image. I've notice that the space between description and image is so much and need to be fixed. Too I've notice that the image is not occupying 100% of the width, exist a border-right that do small the image.

### Screenshot
Our: ![image](https://user-images.githubusercontent.com/66505715/160476767-db321335-3e47-43ff-ba7b-357bff11558c.png)
Original: ![image](https://user-images.githubusercontent.com/66505715/160476788-54d47300-7e31-4065-b8bd-154b0dd8d23d.png)

### Checklist
- [ ] The space between title and subtitle is the same
- [ ] The image is occupying 100% of the width

### References:

Original: http://spgatsbystg.wpengine.com/partners/
Gatsby: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/partners/

**Comment by heliomar-pena** [comment]
Working it

**Comment by heliomar-pena** [comment]
[Pull request](https://github.com/simplepractice/www-simplepractice-gatsby/pull/479)

**Comment by heliomar-pena** [comment]
Done! Please check

[Gatsby](https://wwwsimplepracticegatsbystaging-fixpartnerstemplatespaces.gtsb.io/partners)
[Original](http://spgatsbystg.wpengine.com/partners/)

**Comment by angelik0828** [comment]
fixed!
