### ISSUE TITLE
image text is not centered -  shopeasy-ruby-backend

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#94]
### Explanation
the text of the image is not centered with respect to the image.

**Actual result:** the text of the image is not centered

**Expected result:** Make sure the text is centered in relation to the image.

*Screen size:* all screen

### Screenshots

Our: 
![image](https://user-images.githubusercontent.com/103531307/166712491-67be8f6c-4081-4b27-9eb3-1e79053b9408.png)

### Checklist

This issue can be closed when the following tasks are complete:
 
 - [ ] the text in the image is centered.
 
### References

Our: https://github.com/Israel-Laguan/shopeasy-ruby-backend

**Comment by Israel-Laguan** [comment]
This is a design issue, which I think is not valid.
