### ISSUE TITLE
cropped image text - Positioning-and-Floating-Elements

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/various-tasks#95]
### Explanation
The text of the images is cut off.

**Actual result:** the text in the image is not complete.

**Expected result:** the text of the image is complete.

*Screen size:* all screen

### Screenshots

Our: 
![image](https://user-images.githubusercontent.com/103531307/166722648-fd07fc08-6d54-41e0-8ba2-805b197338d6.png)

### Checklist
This issue can be closed when the following tasks are complete:
 
 - [ ] the texts in the images are complete.
 
### References

Our: https://github.com/Israel-Laguan/Positioning-and-Floating-Elements

**Comment by Israel-Laguan** [comment]
In this case, I think it's expected? As was only and example, there is no need to show everything

**Comment by Israel-Laguan** [comment]
I think this is not a valid issue
