### ISSUE TITLE
Alignment box under the title

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#96]
### Explanation
The box below the title is not aligned in a single row for this resolution.

**Actual result:**
When looking at "Proximity Post-it" the view of the box above is seen divided into two rows.

**Expected result:**
That when looking at "Proximity Post-it" the view of the box above is seen in a single row.

*Screen size:*
1024x633

### Screenshots
![image](https://user-images.githubusercontent.com/74306449/166835247-517f0da4-52be-4a2b-bf71-2eff88722639.png)

### Check list
This issue can be closed when the following tasks are completed:

* * fixed the margin bug and the box is seen in a single row for this and all resolutions.
 
### References
 https://github.com/Israel-Laguan/proximity-post-it

**Comment by Israel-Laguan** [comment]
Hmm I think the box is aligned? Maybe you meant to align the labels (like the "FORKS 0")?

**Comment by anaPiris** [comment]
When the screen is opened, it is shown as indicated in the attached link in this comment, as if the bottom box were smaller, when opening the inspector, the bottom box is shown aligned and changes the labels to two rows.
![image](https://user-images.githubusercontent.com/74306449/167048773-9e9f3ffc-13eb-408e-b30f-c18f2bf6330b.png)

**Comment by Israel-Laguan** [comment]
This is the intended behavior, it's normal it becomes 2 rows when the size is small
