### ISSUE TITLE
Title Aligned With The Link  /  Título Alineado Con El Enlace

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#97]
### Explanation:

As a suggestion, the link pasted to the title that references it would be more visible.

**Current result:**
Going through "Task", it is observed that the link is not aligned with the title that refers to it.

**Expected result:**
Hovering over Task", you can see the link aligned with the title that refers to it.

*Screen size:*
1024x633

### Screenshots:
![image](https://user-images.githubusercontent.com/74306449/166836325-008d2bed-c8c5-4447-9795-8f11c878526a.png)

### Check list:
   This issue can be closed when the following tasks are completed:

   - That the title is followed by the link to which it refers.
 
### References:
https://github.com/Israel-Laguan/proximity-post-it

Spanish Version:

### Explicación:

Como sugerencia, el enlace pegado al título que lo referencia sería más visible.

**Resultado actual:**
Al pasar por "Tarea", se observa que el enlace no está alineado con el título que hace referencia al mismo.

**Resultado Esperado:**
Que al pasar el cursor sobre Tarea, se pueda ver el enlace alineado con el título que hace referencia a él.

*Tamaño de pantalla:*
1024x633

### Capturas de pantalla:
![imagen](https://user-images.githubusercontent.com/74306449/166836325-008d2bed-c8c5-4447-9795-8f11c878526a.png)

### Lista de Verificación:
   Este problema se puede cerrar cuando se completen las siguientes tareas:

   - Que al título le siga el enlace al que se refiere.
 
### Referencias:
https://github.com/Israel-Laguan/proximity-post-it

**Comment by mdrianislam0or1** [comment]
aligned link with the title

**Comment by mdrianislam0or1** [comment]
https://github.com/Israel-Laguan/proximity-post-it/pull/80

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171285056-f936a749-5e54-4c56-9b85-ab4720d85f4a.png)
