### ISSUE TITLE
  Margin Alignment And Unified Content   /  Alineación De Márgenes Y Contenido Unificado /

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#98]
### Explanation:
Under "Potential Features - Author", in the top right box where the Linkedin reference is, it should show everything on the same line. On the other hand, the icons in this box are not aligned with the text.

**Current result:**
In "Potential Features- Author" you can see that in the top right box, the "/Connect to my Linkedin" reference is cut off and not correctly aligned.

**Expected result:**
That in "Potential Features- Author", the box on the top right, all the reference of "/Connect to my Linkedin" be seen together and aligned with respect to the text.

*Screen Size:* (Add your screen size)
1-1024x633
2-768x633
3-375x633
### Screenshots:
The inset shows alignment variations depending on the resolution applied:
1-
![image](https://user-images.githubusercontent.com/74306449/166842787-b8427249-5b6a-43a2-83ef-10dc73d7b44c.png)
2-
![image](https://user-images.githubusercontent.com/74306449/166842517-913f8a8f-b605-42f6-9ff0-6a9cf743212f.png)
3-
![image](https://user-images.githubusercontent.com/74306449/166842635-7f51c660-a1fb-43f0-afe1-993c5d1bdcce.png)

### Check list:
This issue can be closed when the following tasks are completed:
- That the correct position of the text and the alignment of the margins be verified for all resolutions.

 ### References:

https://github.com/Israel-Laguan/proximity-post-it
https://github.com/Israel-Laguan/overtime-app

Spanish Version:

### Explicación:
En "Características potenciales - Autor", en el cuadro superior derecho donde está la referencia de Linkedin, debería mostrar todo en la misma línea. Por otro lado, los íconos de este cuadro no están alineados con el texto.

**Resultado actual:**
En "Características potenciales- Autor" se observa que en el recuadro de arriba a la derecha, la referencia de "/Conectar a mi Linkedin" está cortada y no está alineada correctamente.

**Resultado Esperado:**
Que en "Características potenciales- Autor", la casilla de arriba a la derecha, se vea toda la referencia de "/Conectar a mi Linkedin" junta y alineada respecto al texto.

*Tamaño de pantalla:* (Agregue el tamaño de su pantalla)
1-1024x633
2-768x633
3-375x633
### Capturas de pantalla:
El recuadro muestra variaciones de alineación dependiendo de la resolución aplicada:
1-
![imagen](https://user-images.githubusercontent.com/74306449/166842787-b8427249-5b6a-43a2-83ef-10dc73d7b44c.png)
2-
![imagen](https://user-images.githubusercontent.com/74306449/166842517-913f8a8f-b605-42f6-9ff0-6a9cf743212f.png)
3-
![imagen](https://user-images.githubusercontent.com/74306449/166842635-7f51c660-a1fb-43f0-afe1-993c5d1bdcce.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
- Que se verifique la posición correcta del texto y la alineación de los márgenes para todas las resoluciones.

 ### Referencias:
https://github.com/Israel-Laguan/proximity-post-it
https://github.com/Israel-Laguan/overtime-app

**Comment by Israel-Laguan** [comment]
@anaPiris please verify https://github.com/TheRandomCrew/overtime-app/pull/1 if this solves what you found

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171278857-3640e8db-fed1-4340-b767-bedc93eded91.png)
