### ISSUE TITLE
 Text alignment according to resolution

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#99]
### Explanation
The "Parrot Echo" title is not displayed correctly aligned for resolutions other than 1024x633.

**Actual result:**
In "Parrot Echo" the title text is not well aligned for resolutions other than 1024x633.

**Expected result:**
That in "Parrot Echo" the title text is aligned for all resolutions the same as 1024x633.

*Screen Size:* (Add your screen size)
1-1024x633
2-768x633
3-425x633
### Screenshots
The inset shows alignment variations depending on the resolution applied:
1-
![image](https://user-images.githubusercontent.com/74306449/166845485-f2834d4c-ce40-49b3-a5e5-c6388c44bcba.png)

2-
![image](https://user-images.githubusercontent.com/74306449/166845571-1fc8276f-15f1-499d-a7ec-0da1e9c1d59f.png)

3-
![image](https://user-images.githubusercontent.com/74306449/166845765-91f0d8c8-1e0a-4a67-b569-27f7b2dfee61.png)

### Check list
This issue can be closed when the following tasks are completed:
- Verify that the text is aligned for all resolutions.

  ### References
https://github.com/Israel-Laguan/parrot-echo

**Comment by Israel-Laguan** [comment]
This one is expected, I think is the expected behavior, as in a single string of text

**Comment by Israel-Laguan** [comment]
Maybe propose another solution to the title, also @angelik0828 what do you think of this style? Or do you have other suggestions?

**Comment by angelik0828** [comment]
I think lowering the resolution might reduce the size of the text as it would look bad at the same size on a small screen.

and be left on a single line or two but with the text centered

**Comment by Israel-Laguan** [comment]
What about separate in 2 lines?

**Comment by anaPiris** [comment]
De acuerdo con el comentario de Angélica, opino que se vería mejor como lo muestra en la resolución 768x633 y que se vea de la misma forma para las demás resoluciones, excepto la de 1024x633 que el título se ve en una sola línea.
